let options = [

    "VISOR TRANSPARENTE - Precio: $0.15",
    "SET PUNTOS NEGROS - Precio: $5.60", 
    "DESODORANTE ACLARADOR - Precio: $2.75",
    "ORGANIZADOR DE BANO - Precio: $12.75 A PARTIR DE 3 UNIDADES $12.50 C/U",
    "HDMI - Precio: $4.00",
    "PORTA PLATOS - Precio: $3.95 ",
    "ARO DE LUZ - Precio: $8.50 ",
    "SET ONDAS - Precio: $10.50 ",
    "INFLADOR DE PELOTAS Y PISCINA - Precio: $1.10",
    "LUNA MINI FOREVER - Precio: $1.65",
    "ONDULADOR NOVA - Precio: $3.70 ",
    "CEPILLO SECADORA DE PERRO - Precio: $8.75 A PARTIR DE 4 UNIDADES $8.50 C/U",
    "SALIDAS DE BANO Y GORRO - Precio: $6.00",
    "CAJON OCULTO - Precio: $0.95 ",
    "FOCO PARLANTE GRANDE - Precio: $10.50 ",
    "SET SALUD INFANTIL - Precio: $3.00",
    "MESITA PARA TV - Precio: $2.50 ",
    "ORGANIZADOR DE SALSAS - Precio: $4.00",
    "SET DE LIGAS DE CINCO - Precio: $1.85 ",
    "COMBO PASTELERO - Precio: $11.75 ",
    "PORTA TAZAS MEDIANO - Precio: $1.05 ",
    "SEIS GUANTES DE OLLA - Precio: $2.90 ",
    "SOPORTE DE TV - Precio: $2.90 ",
    "LIMPIA OLLA - Precio: $1.15",
    "LIGAS DE HOMBRE - Precio: $4.00",
    "ALCANCIA POLICIA - Precio: $14.00",
    "KIT EJERCITATE - Precio: $10.50 ",
    "ROPERO TRES CUERPOS - Precio: $20.25 ",
    "DISPENSADOR DE JABON MASCOTAS - Precio: $1.50 ",
    "PLATERA COLORES - Precio: $12.00",
    "ATRAPA PELUZAS - Precio: $3.40 ",
    "ESCURRIDOR DE FRUTAS - Precio: $2.00",
    "INFLADOR DE LLANTAS - Precio: $8.00",
    "SPRAY DE ACEITE - Precio: $1.50 ",
    "OLLA DE CERA - Precio: $6.75 ",
    "SET BLANQUEADOR COMPLETO - Precio: $3.25",
    "SET CINTILLO Y RODILLO FACIAL - Precio: $2.75 ",
    "DOCE COLAGENO DE LABIOS - Precio: $2.30 ",
    "TENDEDERO DE ROPA - Precio: $14.75 ",
    "JABONERA COLORES - Precio: $0.75 ",
    "HUMIFICADOR FLORERO - Precio: $5.00",
    "TAPETE PARA AMASAR - Precio: $1.25 ",
    "LIMPIA VIDRIO - Precio: $1.25 ",
    "CAMARA IP - Precio: $23.50 ",
    "PORTA CUCHARONES - Precio: $1.00",
    "ICE ROLLER - Precio: $2.75 ",
    "SEIS MASKS TRES PASOS EN SOBRE - Precio: $3.75 ",
    "FLEX TAPE - Precio: $1.00",
    "SEIS TOALLAS DE COCINA - Precio: $2.75 ",
    "DESTAPA CORCHO - Precio: $8.00",
    "TRAPEADOR PORTATIL - Precio: $4.00",
    "INFLADOR DE GLOBOS - Precio: $12.00",
    "COMBO HOGAR LIMPIO - Precio: $7.90 ",
    "REPISA MULTIUSO - Precio: $5.50 ",
    "TIRA LED GRANDE - Precio: $6.50 ",
    "TIRA LED PEQUENA - Precio: $3.65 ",
    "MOLDES DE TORTA - Precio: $6.25 ",
    "ESQUINERO DE BANO - Precio: $10.00 ",
    "MAQUINA PARA YOGURT - Precio: $5.50 ",
    "CAJA DE 10 MASCARILLAS FACIALES - Precio: $3.00",
    "ROPERO DOS CUERPOS - Precio: $13.75 ",
    "SEIS ESTRELLAS DE COCINA - Precio: $2.90 ",
    "CAJA DE DESINFECCION - Precio: $4.75 ",
    "DISPENSADOR DE CEREAL POR DOS - Precio: $12.50 ",
    "MASAJEADOR CORPORAL - Precio: $5.25 ",
    "JUEGO DE CEVICHERAS - Precio: $3.75 ",
    "TECLADO - Precio: $3.65",
    "TOLDO DOS PLAZAS - Precio: $9.90 ",
    "ARO DE LUZ DIEZ PULGADAS - Precio: $12.50 ",
    "CEPILLO Y EXTRACTOR DE PUNTOS - Precio: $10.75 ",
    "ARO DE LUZ Y CEPILLO - Precio: $14.75 ",
    "DISPENSADOR DE AGUA - Precio: $2.75 ",
    "PAR DE GUANTES - Precio: $1.50 ",
    "ARO DE LUZ Y FOCO ESPEJO - Precio: $12.25 ",
    "LAMINAS LIMPIADORAS - Precio: $1.25 ",
    "PELOTA YOGA - Precio: $4.50 ",
    "TENSIOMETRO DE MUNECA - Precio: $7.90 ",
    "ESPONJA SILICON - Precio: $1.20 ",
    "FOCO ESPEJO - Precio: $4.25 ",
    "FOCO CAMARA - Precio: $13.50 ",
    "COLGADOR DE ROPA - Precio: $10.00 ",
    "SILICONE PARA LIMPIAR BANO - Precio: $1.45",
    "MICROFONO - Precio: $3.90 ",
    "LICUADORA - Precio: $4.50 ",
    "DOCE COLAGENOS DE OJOS - Precio: $2.25 ",
    "TREINTA TARJETAS VIRUS - Precio: $1.00",
    "ESFERA ARO - Precio: $5.50",
    "SOSTENEDOR DE PUERTA - Precio: $2.00",
    "SEIS MASCARILLAS BIOAQUA - Precio: $2.30",
    "CORRECTOR DE ESPALDA - Precio: $3.00",
    "PROYECTOR - Precio: $2.75 ",
    "SERUM VITAMIN C - Precio: $1.80 ",
    "KIT TRES PASOS BIOAQUA - Precio: $2.80 ",
    "COLGADOR PARA PUERTAS - Precio: $2.50 ",
    "VENTILADOR - Precio: $6.95 ",
    "PUSH UP BRA - Precio: $1.25 ",
    "CAJA DE HERRAMIENTA - Precio: $3.75 ",
    "ALFOMBRAS INFANTILES SUBLIMADAS - Precio: $16.80 ",
    "CINTURON PARA CABALLERO - Precio: $4.50 ",
    "PULIDOR DE UNAS GRANDE - Precio: $10.00",
    "ORGANIZADOR CUADRADO - Precio: $4.40 ",
    "FOCO PARLANTE - Precio: $3.90 ",
    "BANDA DE BRASIER - Precio: $1.45 ",
    "TENDEDERO REDONDO - Precio: $10.00",
    "DISPENSADOR DE GASEOSAS - Precio: $2.10 ",
    "CHOCOLATERA - Precio: $9.00",
    "MAQUINA DE PUNTOS NEGROS - Precio: $4.00 ",
    "BOTITAS PARA PERRO - Precio: $2.20 ",
    "CARPA TUNEL - Precio: $16.50 ",
    "PESAS - Precio: $40.00",
    "TREINTA TARJETAS VIRUS KID - Precio: $1.00 ",
    "BLUSA TERMICA - Precio: $3.25 ",
    "RELOJ REPELENTE - Precio: $0.75 ",
    "TRAPEADOR PORTATIL - Precio: $3.50 ",
    "HUEVERA - Precio: $1.20 ",
    "PORTA ESPONJA - Precio: $0.50 ",
    "LUCES TRES METROS - Precio: $8.50 ",
    "TRES COLGADORES DE NUBES - Precio: $1.15 ",
    "PORTA CELULAR - Precio: $0.65 ",
    "MINI IMPRESORA - Precio: $19.50 ",
    "COMBO ACLARADOR - Precio: $4.50 ",
    "MANGUERA - Precio: $5.50",
    "PORTA LAPIZ Y CELULAR - Precio: $3.40 ",
    "CINTA DOBLE CARA - Precio: $1.00",
    "CANGUROS MICKEY - Precio: $4.00",
    "ORGANIZADOR TRES PISOS - Precio: $14.50 ",
    "MESA LAPTOP - Precio: $5.75 ",
    "MAQUINA MASAJES REDUCTORES - Precio: $12.00",
    "RUEDA ABDOMINAL - Precio: $3.95 ",
    "PARRILLA RECTANGULAR - Precio: $9.50 ",
    "TREINTA FUNDAS DESINFECTANTES - Precio: $2.25 ",
    "DOCE CINTILLOS - Precio: $7.50 ",
    "BALANZA - Precio: $7.25 ",
    "NEUBOLIZADOR - Precio: $9.25 ",
    "PAR DE MEDIAS - Precio: $1.75 ",
    "CEPILLO CON DISPENSADOR - Precio: $1.50 ",
    "VASOS PORTATILES - Precio: $1.10 ",
    "SPINNER - Precio: $0.70 ",
    "ESCURRIDOR DE ESPONJA - Precio: $1.35 ",
    "SEIS FILTROS ADAPTADORES - Precio: $3.50 ",
    "TALADRO - Precio: $11.50 ",
    "TRIPODE - Precio: $1.25 ",
    "PELUCHE MANTA - Precio: $7.50 ",
    "CUERDA DIGITAL - Precio: $2.75 ",
    "SACA ESCAMAS - Precio: $0.70 ",
    "CANGUILERA - Precio: $11.25 ",
    "BLANQUADOR DE DIENTES - Precio: $2.00",
    "CEPILLO DE DUCHA - Precio: $0.80 ",
    "UNICORNIO CON MANTA - Precio: $11.75 ",
    "LENTES DE CONTACTO - Precio: $7.50 ",
    "FREIDORA - Precio: $44.00",
    "ESTRELLAS DESENREDANTES - Precio: $0.55 ",
    "SET DE CUBIERTOS - Precio: $17.50 ",
    "OXIMETRO - Precio: $3.50 ",
    "ABLANDADOR DE CARNES - Precio: $1.25 ",
    "GORRO DE BANO - Precio: $1.10",
    "BOLSA PARA LAVAR BRASIER - Precio: $1.00",
    "MASAJEADOR FACIAL DE VIDRIO - Precio: $5.25",
    "ALUMINIO PARA HORNILLAS - Precio: $1.75 ",
    "SET SALUD - Precio: $12.75 ",
    "CEPILLO SECADOR - Precio: $7.25 A PARTIR DE 3 UNIDADES $7.00 C / U ",
    "DOCE PASTILLAS PARA BANO - Precio: $0.80 ",
    "CARPA TOLDO CELESTE - Precio: $12.50 ",
    "MAGIC PACK - Precio: $3.50 ",
    "FOCO TRES ALAS - Precio: $3.40 ",
    "MAQUINA DE ALGODON DE AZUCAR - Precio: $18.50 ",
    "PISTOLA BURBUJA - Precio: $2.75 ",
    "TIRA DE SILICON PARA DUCHA - Precio: $1.25 ",
    "ESFERA PROYECTORA - Precio: $4.50 ",
    "JUEGO DE CUCHILLOS - Precio: $7.50 ",
    "TOMATODOS - Precio: $2.75 ",
    "TOLDO REDONDO DOS PLAZAS - Precio: $9.50 ",
    "DISPENSADOR DE PASTA UV - Precio: $4.50 ",
    "SET DE TRES SERUMS - Precio: $3.75 ",
    "HUMIFICADOR COCO - Precio: $4.50 ",
    "MAQUINA PINTURA - Precio: $20.50 ",
    "DISPENSADOR DE GRANOS UN COMPARTIMIENTO - Precio: $2.95 ",
    "ROLLO DE ALUMINIO TRES METROS - Precio: $1.90 ",
    "SEPARADOR DE LLEMA - Precio: $0.20 ",
    "SESENTA COLAGENOS DE LABIOS - Precio: $2.20",
    "CERCA DE HOJAS - Precio: $8.00",
    "PORTA SERVILLETA - Precio: $3.95 ",
    "VISOR ACRILICO - Precio: $0.95 ",
    "KID DE CEJAS - Precio: $2.00",
    "COMBO MORENA - Precio: $7.25 ",
    "ARBOL DE NAVIDAD - Precio: $36.00",
    "LONCHERA ELECTRICA - Precio: $4.75 ",
    "COMBO COLAGENO - Precio: $8.80 ",
    "SEIS LABIALES MAGICO - Precio: $3.40 ",
    "PLATERA DE DOS POZOS - Precio: $22.50 ",
    "TABLA PICAR - Precio: $2.00",
    "ZAPATERA VARIOS COLORES - Precio: $13.50 ",
    "ORGANIZADOR DE CONDIMENTOS - Precio: $8.50 ",
    "AFILADOR DE CUCHILLOS - Precio: $2.05 ",
    "LIGAS DE RESISTENCIA - Precio: $3.50 ",
    "ALCANCIA DIGITAL - Precio: $4.50 ",
    "MOLINO DE CARNE - Precio: $8.50 ",
    "MAQUINA DE COSER - Precio: $8.50 ",
    "SET INFANTIL - Precio: $13.75 ",
    "PELUCHE ABRIGO - Precio: $6.50 ",
    "ORGANIZADOR OCULTO - Precio: $9.50 ",
    "SARTEN DE HUEVO - Precio: $0.95 ",
    "ASPIRADORA DE AUTO - Precio: $6.25 ",
    "SACA CALLO - Precio: $2.75 ",
    "BATIDORA - Precio: $5.95 ",
    "GAFAS WIFI - Precio: $6.75 ",
    "PICATODO ELECTRICO - Precio: $10.50 ",
    "GREEN MASK - Precio: $1.40 ",
    "ELEFANTE MUSICAL - Precio: $8.50 ",
    "MAQUINA LIMPIA BROCHAS - Precio: $0.80 ",
    "BANDEJAS DE REFRIGERADOR - Precio: $0.80 ",
    "DESTAPA TUBERIAS - Precio: $0.65 ",
    "AZUCARERA - Precio: $3.30 ",
    "REFRIGERADOR - Precio: $25.80 ",
    "KIT DEPILACION Y ROSTRO - Precio: $10.50 ",
    "COMBO ROSTRO LINDO - Precio: $3.50 ",
    "COMBO MADI - Precio: $13.80 ",
    "CIGARILLOS - Precio: $1.50 ",
    "KIT PUNTOS NEGROS - Precio: $6.85 ",
    "TENSIOMETRO - Precio: $9.50 ",
    "CREMA Y SPLASH - Precio: $3.50 ",
    "COMBO DANIELA - Precio: $11.75 ",
    "MINI LAVADORA - Precio: $2.50 ",
    "SEIS TAPAS DE SILICON - Precio: $1.00",
    "CUCHILLOS Y MOLINO - Precio: $14.50 ",
    "PLANCHA BABOYIESS - Precio: $10.75 ",
    "PLANCHA NEGRA - Precio: $5.75 ",
    "DUO PERFECTO - Precio: $12.00",
    "ALMOHADA - Precio: $3.50 ",
    "COMBO BELLEZA - Precio: $18.50 ",
    "CEPILLO Y FOREVER - Precio: $8.25",
    "COMBO COLAGENO Y FOREVER - Precio: $4.35 ",
    "ARO Y FOREVER - Precio: $9.75",
    "COMBO NUDE - Precio: $10.75 ",
    "COMBO GABRIELA - Precio: $12.75 ",
    "PESTANAS - Precio: $2.00",
    "AFILADOR ARCO - Precio: $1.95 ",
    "ASPIRADORA DE CARRO TIPO DOS - Precio: $6.50 ",
    "FOCO PARLANTE TRES ALAS - Precio: $9.50 ",
    "COLGADOR TOTALMENTE METALICO - Precio: $6.50 ",
    "UNA HORNILLA - Precio: $6.75 ",
    "WAFLERA - Precio: $12.75 ",
    "MAQUINA MASCARA - Precio: $21.00",
    "CREPERA - Precio: $13.50 ",
    "SACA PELUZA - Precio: $2.25 ",
    "MICKEY O MINIE - Precio: $16.50 ",
    "TACHO CON MOPA - Precio: $7.50 ",
    "FOCO PARLANTE - Precio: $3.90 ",
    "DISPENSADOR DE FUNDAS - Precio: $2.25 ",
    "HUEVERA ELECTRICA - Precio: $4.60 ",
    "ESCURRIDOR DE LEGUMBRES - Precio: $1.45 ",
    "CORRECTOR DE POSTURA CON SENSOR - Precio: $3.00",
    "MINI CAMARA - Precio: $4.25 ",
    "ESTUDIO FOTOGRAFICO - Precio: $4.00",
    "TRAPEADOR CON SPLASH - Precio: $7.75 ",
    "MARTILLO MULTIUSO - Precio: $8.00",
    "LONCHERA CUATRO COMPARTIMIENTOS - Precio: $2.25 ",
    "ADAPTADOR DE LLAVE - Precio: $1.75 ",
    "AUDIFONOS INALAMBRICOS - Precio: $7.75 ",
    "CANDADO CON ALARMA - Precio: $6.00 ",
    "LAVADORA DE ROPA INTERIOR - Precio: $29.00 ",
    "MANTA QUE BRILLA - Precio: $8.50 ",
    "FORRO PARA MOTO - Precio: $2.95 ",
    "AFEITADORA GOLDEN - Precio: $5.50 ",
    "MANTA PERRITO - Precio: $11.00",
    "MASCARILLA PARA PIES - Precio: $1.35 ",
    "SHOES RACK - Precio: $6.25 ",
    "ELEFANTE - Precio: $5.75 ",
    "SOPORTE DE LAVADORA - Precio: $6.50 ",
    "PASTILLAS PARA LAVADORA - Precio: $1.25 ",
    "SOPORTE PARA CELULAR - Precio: $1.25 ",
    "PIJAMAS PARA DAMAS - Precio: $8.50 ",
    "JUEGO INTERIOR - Precio: $6.50 ",
    "DISPENSADOR DE FREJOL GRANDE - Precio: $11.50 A PARTIR DE 3 UNIDADES $11.00 C/U", 
    "COMBO TITANIUM - Precio: $11.50 ",
    "LABIALES KYLIE - Precio: $4.50 ",
    "LUZ LED SOLAR - Precio: $5.60 ",
    "PLANCHA SONAR - Precio: $9.00",
    "SARTENES CORAZON - Precio: $1.85 ",
    "PASTILLERO - Precio: $4.00 ",
    "ALFOMBRA UNICORNIO - Precio: $11.50 ",
    "PARLANTE PEQUENO - Precio: $4.75 ",
    "ONDULADOR CEPILLO - Precio: $2.70 ",
    "PARLANTE GRANDE - Precio: $26.50 ",
    "CORTINAS LED - Precio: $8.90 ",
    "LUZ PORTATIL - Precio: $4.00",
    "ORGANIZADOR DE CABLES - Precio: $0.60 ",
    "GUANTE PARA OBJETOS CALIENTES - Precio: $0.45 ",
    "MASAJEADOR CORPORAL - Precio: $5.25 ",
    "FORRO DE MUEBLE - Precio: $10.50 ",
    "FORRO DE MUEBLE DOS PUESTOS - Precio: $9.50 ",
    "OSO REFLECTOR BLANCO - Precio: $7.00",
    "JABON FACIAL - Precio: $2.25",
    "ESFOLIANTES CORPORALES - Precio: $2.30",
    "SEIS EXFO EN GEL - Precio: $4.00",
    "CREMA CORPORAL - Precio: $1.90 ",
    "SCREEN FINGERTIPS - Precio: $0.65",
    "SUPER COMBO BLANQUEADOR - Precio: $7.90",
    "ONDULADOR TRIPLE - Precio: $10.00",
    "TVBOX ULTIMA VERSION - Precio: $18.40",
    "ASADOR DE CARNE - Precio: $24.00",
    "PORTA CELULAR ADHESIVO - Precio: $1.75 ",
    "HONGO PARLANTE - Precio: $2.95 ",
    "RELOJES MARGARITAS - Precio: $4.95 ",
    "COMBO AFILADOR CUCHILLOS LONCHERA - Precio: $11.75 ",
    "COMBO ROSA PASTEL - Precio: $11.55 ",
    "BIOAQUA MASCARA DE OJOS - Precio: $2.75 ",
    "SET BIOAQUA - Precio: $6.25 ",
    "COMBO VITAMIN C - Precio: $7.25 ",
    "COMBO GOLD - Precio: $6.50 ",
    "BANDAS PUNTOS NEGROS - Precio: $1.50 A PARTIR DE 3 UNIDADES $1.25 C/U", 
    "PILDORAS VITAMIN C - Precio: $2.50 ",
    "COMBO AGUACATE Y GOLDEN - Precio: $6.35 ",
    "CUATRO LABIALES HUDA - Precio: $2.00",
    "DOCE MASCARILLAS DE COLAGENO - Precio: $7.00",
    "COMBO RODILLO COLAGENOS Y PAPAYA - Precio: $4.25",
    "GEL FACIAL ALOE VERA - Precio: $1.65 ",
    "COMBO MILK - Precio: $6.00",
    "DELINEADORES NAKED - Precio: $1.00",
    "DESODORANTE BLANQUEADOR - Precio: $2.75 ",
    "DESODORANTE Y CREMA BLANQUEADORA - Precio: $3.50 ",
    "DISPENSADOR DE CEREAL POR UNO - Precio: $7.40 ",
    "COMBO EXTRACTOR FOREVER COLAGENO - Precio: $6.85 ",
    "VEINTICUATRO BROCHAS - Precio: $5.50",
    "MASCARILLA A BASE DE HUEVO - Precio: $2.50 ",
    "BIOAQUA TUBO - Precio: $1.85 ",
    "DESODORANTE PARA CABALLERO - Precio: $2.75 ",
    "MASCARILLAS POR 12 - Precio: $3.90 ",
    "COMBO PAPAYA VITAMINA C - Precio: $7.00",
    "COMBO PRECIOSA - Precio: $7.75 ",
    "COMBO NUDE SOMBRA PEQUENA - Precio: $5.75 ",
    "COMBO SPA - Precio: $5.50 ",
    "COMBO MASK CARBON TRES PASOS - Precio: $2.75 ",
    "SOMBRA COCOA - Precio: $3.25 ",
    "SOMBRA HUDA - Precio: $2.50 ",
    "PERFUMES - Precio: $7.00",
    "AZUCARERA - Precio: $3.30",
    "JUEGO DE VAJILLAS - Precio: $23.50",
    "NEON - Precio: $3.00",
    "COSTO DEL ENVIO - Precio: $4.50",
    "COSTO DEL ENVIO - Precio: $5.50",
    "COSTO DEL ENVIO - Precio: $6.50",
    "COSTO DEL ENVIO - Precio: $7.50",
    "COSTO DEL ENVIO - Precio: $8.50",
    "COSTO DEL ENVIO - Precio: $9.50",
    "COSTO DEL ENVIO - Precio: $10.50",
    "COSTO DEL ENVIO - Precio: $11.50",
    "COSTO DEL ENVIO - Precio: $12.50",
    "COSTO DEL ENVIO - Precio: $13.50",
    "COSTO DEL ENVIO - Precio: $14.50",
    "COSTO DEL ENVIO - Precio: $15.50",
    "COSTO DEL ENVIO - Precio: $20.50",
    "MILK FROTHER - Precio: $13.85",
    "SET DE BROCHAS - Precio: $4.95",
    "RELOJ DEPORTIVO PARA CABALLERO - Precio: $4.75",
    "PICATODO NARANJA - Precio: $2.50",
    "CREMA BLANQUEADORA - Precio: $1.25",
    "BATIDORA DE HUEVO - Precio: $1.15",
    "NUEVOS NEONES - Precio: $3.75",
    "COSEDORA PORTATIL - Precio: $1.45",
    "JUGUETE BURBUJA - Precio: $3.45",
    "TACHO CON SENSOR - Precio: $4.95",
    "ALFOMBRA SALDOS - Precio: $15.50",
    "ORGANIZADOR DE ROPA INTERIOR - Precio: $2.50",
    "CORRECTOR DE POSTURA NEGRO - Precio: $2.25",
    "CAMARA TRES ANTENAS - Precio: $14.50",
    "WAFLERA CORAZON - Precio: $12.50",
    "CARPA CASTILLO - Precio: $8.00",
    "VENTILADOR PORTATIL RECARGABLE - Precio: $4.50",
    "TRES EN UNO LUZ VENTILADOR ESPEJO - Precio: $2.25",
    "CUCHARAS Y CEPILLOS FACIALES - Precio: $1.15",																									
    "COLGADOR PARA ZAPATOS  - Precio: $0.95",
    "DISPENSADOR KID - Precio: $9.50",
    "MANTA BRILLANTE NAVIDENA - Precio: $7.50",
    "MESA CON DOS SILLAS  - Precio: $29.50",
    "DESESTRESANTE DE COLORES - Precio: $1.00",
    "SEIS TAPONES - Precio: $2.00",
    "COMBO COCINA - Precio: $13.85",
    "CUCHILLOS ACEITERO TAPAS - Precio: $9.50",
    "CEPILLO Y ONDULADOR RESORTE - Precio: $10.00",
    "PULPO REVERSIBLE - Precio: $1.25",
    "ALFOMBRA YOGA - Precio: $4.25",
    "SET DE PLASTILINAS - Precio: $2.20",
    "SARTEN ELECTRICA - Precio: $6.50",
    "SET DE ESPOJAS - Precio: $2.25",
    "MESA LAPTOP INFANTIL - Precio: $7.00",
    "PROMO DISPENSADOR DE AGUA - Precio: $1.50",
    "PROMO AMPLIFICADOR - Precio: $1.95 A PARTIR DE TRES UNIDADES $1.85 C/U",
    "PROMO PUSH UP - Precio: $1.00",
    "PROMO PORTA CELULAR - Precio: $0.65",
    "PROMO DISPENSADOR DE GASEOSA - Precio: $1.80",
    "PROMO ESPEJO STICKER - Precio: $1.50",
    "PROMO CUERDA DIGITAL - Precio: $2.25",
    "PROMO FOCO PARLANTE ALAS - Precio: $8.95",
    "PROMO DISPENSADOR DE BOLSA - Precio: $1.95",
    "PROMO SACA CALLO - Precio: $2.50",
    "PROMO CORRECTOR CON SENSOR - Precio: $2.70",
    "PROMO RELOJ REPELENTE - Precio: $0.65 A PARTIR DE DOCE UNIDADES $0.60 C/U",
    "PROMO DISPENSADOR DE CEREAL - Precio: $11.50",
    "PROMO MINI IMPRESORA- Precio: $17.50",
    "PROMO TAPE FLEX - Precio: $0.65",
    "PROMO SACA CORCHO- Precio: $7.00",
    "PROMO TIKTOK Y FOCO - Precio: $7.00",
    "PROMO ROPERO TRES CUERPOS - Precio: $19.50",
    "PROMO ZAPATERA DOS CUERPOS - Precio: $13.00",
    "PROMO ALFOMBRA - Precio: $14.25",
    "HAPPY NAPPER - Precio: $7.50",
];