let options = [

    "VISOR TRANSPARENTE - Precio: $0.15",
    "SET PUNTOS NEGROS - Precio: $5.60", 
    "DESODORANTE ACLARADOR - Precio: $2.75",
    "ORGANIZADOR DE BANO - Precio: $12.50",
    "HDMI - Precio: $4.00",
    "PORTA PLATOS - Precio: $3.95 ",
    "ARO DE LUZ - Precio: $8.50 ",
    "SET ONDAS - Precio: $10.50 ",
    "INFLADOR DE PELOTAS Y PISCINA - Precio: $1.10",
    "LUNA MINI FOREVER - Precio: $1.75",
    "ONDULADOR NOVA - Precio: $3.70 ",
    "CEPILLO SECADORA DE PERRO - Precio: $8.75 A PARTIR DE 4 UNIDADES $8.50 C/U",
    "SALIDAS DE BANO Y GORRO - Precio: $6.00",
    "CAJON OCULTO - Precio: $0.95 ",
    "FOCO PARLANTE GRANDE - Precio: $10.50 ",
    "SET SALUD INFANTIL - Precio: $3.00",
    "MESITA PARA TV - Precio: $2.50 ",
    "ORGANIZADOR DE SALSAS - Precio: $4.00",
    "SET DE LIGAS DE CINCO - Precio: $1.75 ",
    "COMBO PASTELERO - Precio: $11.75 ",
    "PORTA TAZAS MEDIANO - Precio: $1.05 ",
    "SEIS GUANTES DE OLLA - Precio: $2.90 ",
    "SOPORTE DE TV - Precio: $2.90 ",
    "LIMPIA OLLA - Precio: $1.15",
    "LIGAS DE HOMBRE - Precio: $3.95",
    "ALCANCIA POLICIA - Precio: $14.00",
    "KIT EJERCITATE - Precio: $10.25",
    "ROPERO TRES CUERPOS - Precio: $19.50 ",
    "DISPENSADOR DE JABON MASCOTAS - Precio: $1.50 ",
    "PLATERA COLORES - Precio: $11.75",
    "ATRAPA PELUZAS - Precio: $3.40 ",
    "ESCURRIDOR DE FRUTAS - Precio: $2.00",
    "INFLADOR DE LLANTAS - Precio: $8.00",
    "SPRAY DE ACEITE - Precio: $1.50 ",
    "OLLA DE CERA - Precio: $6.75 ",
    "SET BLANQUEADOR COMPLETO - Precio: $3.25",
    "SET CINTILLO Y RODILLO FACIAL - Precio: $2.75 ",
    "DOCE COLAGENO DE LABIOS - Precio: $2.20",
    "TENDEDERO DE ROPA - Precio: $13.75 ",
    "JABONERA COLORES - Precio: $0.75 ",
    "HUMIFICADOR FLORERO - Precio: $5.00",
    "TAPETE PARA AMASAR - Precio: $1.20",
    "LIMPIA VIDRIO - Precio: $0.95 ",
    "CAMARA IP - Precio: $23.50 ",
    "PORTA CUCHARONES - Precio: $1.00",
    "ICE ROLLER - Precio: $2.75 ",
    "SEIS MASKS TRES PASOS EN SOBRE - Precio: $3.75 ",
    "FLEX TAPE - Precio: $1.00",
    "SEIS TOALLAS DE COCINA - Precio: $2.75 ",
    "DESTAPA CORCHO - Precio: $6.75",
    "TRAPEADOR PORTATIL - Precio: $4.00",
    "INFLADOR DE GLOBOS - Precio: $12.00",
    "COMBO HOGAR LIMPIO - Precio: $7.90 ",
    "REPISA MULTIUSO - Precio: $5.50 ",
    "TIRA LED GRANDE - Precio: $6.50 ",
    "TIRA LED PEQUENA - Precio: $3.75 ",
    "MOLDES DE TORTA - Precio: $6.25 ",
    "ESQUINERO DE BANO - Precio: $10.00 ",
    "MAQUINA PARA YOGURT - Precio: $4.95 ",
    "CAJA DE 10 MASCARILLAS FACIALES - Precio: $3.00",
    "ROPERO DOS CUERPOS - Precio: $13.00 ",
    "SEIS ESTRELLAS DE COCINA - Precio: $2.90 ",
    "CAJA DE DESINFECCION - Precio: $4.75 ",
    "DISPENSADOR DE CEREAL POR DOS - Precio: $12.50 ",
    "MASAJEADOR CORPORAL - Precio: $4.25 ",
    "JUEGO DE CEVICHERAS - Precio: $3.75 ",
    "TECLADO - Precio: $3.65",
    "ARO DE LUZ DIEZ PULGADAS - Precio: $12.50 ",
    "CEPILLO Y EXTRACTOR DE PUNTOS - Precio: $10.75 ",
    "ARO DE LUZ Y CEPILLO - Precio: $14.75 ",
    "DISPENSADOR DE AGUA - Precio: $2.75 ",
    "PAR DE GUANTES - Precio: $1.50 ",
    "LAMINAS LIMPIADORAS - Precio: $1.25 ",
    "PELOTA YOGA - Precio: $4.95 ",
    "TENSIOMETRO DE MUNECA - Precio: $7.90 ",
    "ESPONJA SILICON - Precio: $1.20 ",
    "FOCO ESPEJO - Precio: $4.25 ",
    "FOCO CAMARA - Precio: $13.50 ",
    "COLGADOR DE ROPA - Precio: $10.00 ",
    "SILICONE PARA LIMPIAR BANO - Precio: $1.45",
    "MICROFONO - Precio: $3.95 ",
    "LICUADORA - Precio: $4.50 ",
    "DOCE COLAGENOS DE OJOS - Precio: $2.20",
    "TREINTA TARJETAS VIRUS - Precio: $1.00",
    "ESFERA ARO - Precio: $5.50",
    "SOSTENEDOR DE PUERTA - Precio: $2.00",
    "SEIS MASCARILLAS BIOAQUA - Precio: $2.30",
    "CORRECTOR DE ESPALDA - Precio: $3.00",
    "PROYECTOR - Precio: $2.75 ",
    "SERUM VITAMIN C - Precio: $1.80 ",
    "KIT TRES PASOS BIOAQUA - Precio: $2.80 ",
    "COLGADOR PARA PUERTAS - Precio: $2.50 ",
    "VENTILADOR - Precio: $6.95 ",
    "PUSH UP BRA - Precio: $1.25 ",
    "CAJA DE HERRAMIENTA - Precio: $3.75 ",
    "ALFOMBRAS INFANTILES SUBLIMADAS - Precio: $17.50 ",
    "CINTURON PARA CABALLERO - Precio: $4.50 ",
    "PULIDOR DE UNAS GRANDE - Precio: $10.00",
    "ORGANIZADOR CUADRADO - Precio: $4.40 ",
    "FOCO PARLANTE - Precio: $3.65 A PARTIR DE 3 UNIDADES $3.50 C/U",
    "BANDA DE BRASIER - Precio: $1.45 ",
    "TENDEDERO REDONDO - Precio: $10.00",
    "DISPENSADOR DE GASEOSAS - Precio: $2.10 ",
    "CHOCOLATERA - Precio: $8.50",
    "MAQUINA DE PUNTOS NEGROS - Precio: $4.00 ",
    "BOTITAS PARA PERRO - Precio: $2.20 ",
    "CARPA TUNEL - Precio: $17.50 ",
    "PESAS - Precio: $40.00",
    "TREINTA TARJETAS VIRUS KID - Precio: $1.00 ",
    "BLUSA TERMICA - Precio: $3.25 ",
    "RELOJ REPELENTE - Precio: $0.65 A PARTIR DE 12 UNIDADES $0.60 C/U",
    "TRAPEADOR PORTATIL - Precio: $3.50 ",
    "HUEVERA - Precio: $1.25",
    "PORTA ESPONJA - Precio: $0.50 ",
    "LUCES TRES METROS - Precio: $8.50 ",
    "TRES COLGADORES DE NUBES - Precio: $1.15 ",
    "PORTA CELULAR - Precio: $0.65 ",
    "MINI IMPRESORA - Precio: $16.50 ",
    "COMBO ACLARADOR - Precio: $4.50 ",
    "MANGUERA - Precio: $6.50",
    "PORTA LAPIZ Y CELULAR - Precio: $3.25 ",
    "CINTA DOBLE CARA - Precio: $1.00",
    "CANGUROS MICKEY - Precio: $4.00",
    "ORGANIZADOR TRES PISOS - Precio: $13.50 ",
    "MESA LAPTOP - Precio: $5.75 ",
    "MAQUINA MASAJES REDUCTORES - Precio: $12.00",
    "RUEDA ABDOMINAL - Precio: $3.95 ",
    "PARRILLA RECTANGULAR - Precio: $9.25",
    "TREINTA FUNDAS DESINFECTANTES - Precio: $2.10 ",
    "DOCE CINTILLOS - Precio: $7.50 ",
    "BALANZA - Precio: $7.25 ",
    "NEUBOLIZADOR - Precio: $9.25 ",
    "PAR DE MEDIAS - Precio: $1.75 ",
    "CEPILLO CON DISPENSADOR - Precio: $1.45",
    "VASOS PORTATILES - Precio: $1.20 ",
    "SPINNER - Precio: $0.95 A PARTIR DE 3 UNIDADES $0.85 C/U",
    "ESCURRIDOR DE ESPONJA - Precio: $1.45 ",
    "SEIS FILTROS ADAPTADORES - Precio: $3.50 ",
    "TALADRO - Precio: $11.50 ",
    "TRIPODE - Precio: $1.25 ",
    "PELUCHE MANTA - Precio: $7.50 ",
    "CUERDA DIGITAL - Precio: $2.75 ",
    "SACA ESCAMAS - Precio: $0.70 ",
    "CANGUILERA - Precio: $11.25 ",
    "BLANQUADOR DE DIENTES - Precio: $2.00",
    "CEPILLO DE DUCHA - Precio: $0.80 ",
    "UNICORNIO CON MANTA - Precio: $11.75 ",
    "LENTES DE CONTACTO - Precio: $7.50 ",
    "FREIDORA - Precio: $44.00",
    "ESTRELLAS DESENREDANTES - Precio: $0.55 ",
    "SET DE CUBIERTOS - Precio: $17.50 ",
    "OXIMETRO - Precio: $3.50 ",
    "ABLANDADOR DE CARNES - Precio: $1.25 ",
    "GORRO DE BANO - Precio: $1.10",
    "BOLSA PARA LAVAR BRASIER - Precio: $1.00",
    "MASAJEADOR FACIAL DE VIDRIO - Precio: $5.25",
    "ALUMINIO PARA HORNILLAS - Precio: $1.75",
    "SET SALUD - Precio: $12.75 ",
    "CEPILLO SECADOR - Precio: $7.25 A PARTIR DE 3 UNIDADES $7.00 C / U ",
    "DOCE PASTILLAS PARA BANO - Precio: $0.80 ",
    "CARPA TOLDO CELESTE - Precio: $13.50 ",
    "MAGIC PACK - Precio: $3.50 ",
    "FOCO TRES ALAS - Precio: $3.40 ",
    "MAQUINA DE ALGODON DE AZUCAR - Precio: $18.50 ",
    "PISTOLA BURBUJA - Precio: $2.75 ",
    "TIRA DE SILICON PARA DUCHA - Precio: $1.25 ",
    "ESFERA PROYECTORA - Precio: $4.50 ",
    "JUEGO DE CUCHILLOS - Precio: $7.50 ",
    "TOMATODOS - Precio: $2.75 ",
    "TOLDO REDONDO DOS PLAZAS - Precio: $9.50 ",
    "DISPENSADOR DE PASTA UV - Precio: $4.75 ",
    "SET DE TRES SERUMS - Precio: $3.75 ",
    "HUMIFICADOR COCO - Precio: $4.75",
    "MAQUINA PINTURA - Precio: $20.50 ",
    "DISPENSADOR DE GRANOS UN COMPARTIMIENTO - Precio: $2.95 ",
    "ROLLO DE ALUMINIO TRES METROS - Precio: $1.90 ",
    "SEPARADOR DE LLEMA - Precio: $0.20 ",
    "SESENTA COLAGENOS DE LABIOS - Precio: $2.20",
    "CERCA DE HOJAS - Precio: $7.60",
    "VISOR ACRILICO - Precio: $0.95 ",
    "KID DE CEJAS - Precio: $2.00",
    "COMBO MORENA - Precio: $7.25 ",
    "ARBOL DE NAVIDAD - Precio: $36.00",
    "LONCHERA ELECTRICA - Precio: $4.75 ",
    "COMBO COLAGENO - Precio: $8.80 ",
    "SEIS LABIALES MAGICO - Precio: $3.40 ",
    "PLATERA DE UN POZO - Precio: $22.50 ",
    "TABLA PICAR - Precio: $2.00",
    "ZAPATERA VARIOS COLORES - Precio: $13.25 ",
    "ORGANIZADOR DE CONDIMENTOS - Precio: $8.50 ",
    "AFILADOR DE CUCHILLOS - Precio: $2.05 ",
    "LIGAS DE RESISTENCIA - Precio: $3.50 ",
    "ALCANCIA DIGITAL - Precio: $4.50 ",
    "MOLINO DE CARNE - Precio: $8.50 ",
    "MAQUINA DE COSER - Precio: $8.50 ",
    "SET INFANTIL - Precio: $13.75 ",
    "PELUCHE ABRIGO - Precio: $6.50 ",
    "ORGANIZADOR OCULTO - Precio: $9.50 ",
    "SARTEN DE HUEVO - Precio: $1.25 ",
    "ASPIRADORA DE AUTO - Precio: $6.25 ",
    "SACA CALLO - Precio: $2.75 ",
    "BATIDORA - Precio: $5.75 ",
    "GAFAS WIFI - Precio: $6.75 ",
    "PICATODO ELECTRICO - Precio: $10.50 ",
    "GREEN MASK - Precio: $1.40 ",
    "ELEFANTE MUSICAL - Precio: $8.50 ",
    "MAQUINA LIMPIA BROCHAS - Precio: $0.80 ",
    "BANDEJAS DE REFRIGERADOR - Precio: $0.80 ",
    "DESTAPA TUBERIAS - Precio: $0.65 ",
    "AZUCARERA - Precio: $3.50 ",
    "REFRIGERADOR - Precio: $25.80 ",
    "KIT DEPILACION Y ROSTRO - Precio: $10.50 ",
    "COMBO ROSTRO LINDO - Precio: $3.50 ",
    "COMBO MADI - Precio: $13.00 ",
    "CIGARILLOS - Precio: $1.50 ",
    "KIT PUNTOS NEGROS - Precio: $6.85 ",
    "TENSIOMETRO - Precio: $9.50 ",
    "CREMA Y SPLASH - Precio: $3.50 ",
    "COMBO DANIELA - Precio: $11.75 ",
    "MINI LAVADORA - Precio: $2.50 ",
    "SEIS TAPAS DE SILICON - Precio: $1.00",
    "CUCHILLOS Y MOLINO - Precio: $14.50 ",
    "PLANCHA BABOYIESS - Precio: $10.75 ",
    "PLANCHA NEGRA - Precio: $5.75 ",
    "DUO PERFECTO - Precio: $12.00",
    "ALMOHADA - Precio: $3.50 ",
    "COMBO BELLEZA - Precio: $18.50 ",
    "CEPILLO Y FOREVER - Precio: $8.25",
    "COMBO COLAGENO Y FOREVER - Precio: $4.35 ",
    "ARO Y FOREVER - Precio: $9.75",
    "COMBO NUDE - Precio: $10.75 ",
    "COMBO GABRIELA - Precio: $12.75 ",
    "PESTANAS - Precio: $2.00",
    "AFILADOR ARCO - Precio: $1.95 ",
    "ASPIRADORA DE CARRO TIPO DOS - Precio: $6.50 ",
    "FOCO PARLANTE TRES ALAS - Precio: $9.50 ",
    "COLGADOR TOTALMENTE METALICO - Precio: $6.50 ",
    "UNA HORNILLA - Precio: $5.90",
    "WAFLERA - Precio: $12.00 A PARTIR DE 3 UNIDADES $11.50 C/U",
    "MAQUINA MASCARA - Precio: $21.00",
    "CREPERA - Precio: $13.50 ",
    "SACA PELUZA - Precio: $2.25 ",
    "MICKEY O MINIE - Precio: $16.50 ",
    "TACHO CON MOPA - Precio: $7.50 ",
    "FOCO PARLANTE - Precio: $3.90 ",
    "DISPENSADOR DE FUNDAS - Precio: $2.25 ",
    "HUEVERA ELECTRICA - Precio: $4.95 ",
    "ESCURRIDOR DE LEGUMBRES - Precio: $1.45 ",
    "CORRECTOR DE POSTURA CON SENSOR - Precio: $3.00",
    "MINI CAMARA - Precio: $4.25 ",
    "ESTUDIO FOTOGRAFICO - Precio: $4.00",
    "TRAPEADOR CON SPLASH - Precio: $7.75 ",
    "MARTILLO MULTIUSO - Precio: $8.00",
    "LONCHERA CUATRO COMPARTIMIENTOS - Precio: $2.25 ",
    "ADAPTADOR DE LLAVE - Precio: $1.75 ",
    "AUDIFONOS INALAMBRICOS - Precio: $7.75 ",
    "CANDADO CON ALARMA - Precio: $6.00 ",
    "LAVADORA DE ROPA INTERIOR - Precio: $29.00 ",
    "MANTA QUE BRILLA - Precio: $8.25",
    "FORRO PARA MOTO - Precio: $2.95 ",
    "AFEITADORA GOLDEN - Precio: $5.50 ",
    "MANTA PERRITO - Precio: $11.00",
    "MASCARILLA PARA PIES - Precio: $1.25 A PARTIR DE 6 UNIDADES $1.05 C/U",
    "SHOES RACK - Precio: $6.25 ",
    "ELEFANTE - Precio: $5.75 ",
    "SOPORTE DE LAVADORA - Precio: $6.50 ",
    "PASTILLAS PARA LAVADORA - Precio: $1.25 ",
    "SOPORTE PARA CELULAR - Precio: $1.25 ",
    "PIJAMAS PARA DAMAS - Precio: $8.50 ",
    "JUEGO INTERIOR - Precio: $6.50 ",
    "DISPENSADOR DE FREJOL GRANDE - Precio: $11.50 A PARTIR DE 3 UNIDADES $11.00 C/U", 
    "COMBO TITANIUM - Precio: $11.50 ",
    "LABIALES KYLIE - Precio: $4.50 ",
    "LUZ LED SOLAR - Precio: $5.20 ",
    "PLANCHA SONAR - Precio: $9.00",
    "SARTENES CORAZON - Precio: $1.75 ",
    "PASTILLERO - Precio: $3.95",
    "ALFOMBRA UNICORNIO - Precio: $11.50 ",
    "PARLANTE PEQUENO - Precio: $4.75 ",
    "ONDULADOR CEPILLO - Precio: $2.70 ",
    "PARLANTE GRANDE - Precio: $26.50 ",
    "CORTINAS LED - Precio: $8.95 ",
    "LUZ PORTATIL - Precio: $4.00",
    "ORGANIZADOR DE CABLES - Precio: $0.60 ",
    "GUANTE PARA OBJETOS CALIENTES - Precio: $0.45 ",
    "FORRO DE MUEBLE - Precio: $10.50 ",
    "FORRO DE MUEBLE DOS PUESTOS - Precio: $9.50 ",
    "OSO REFLECTOR BLANCO - Precio: $7.00",
    "JABON FACIAL - Precio: $2.25",
    "ESFOLIANTES CORPORALES - Precio: $2.75 A PARTIR DE 3 UNIDADES $2.50 C/U",
    "SEIS EXFO EN GEL - Precio: $3.95",
    "CREMA CORPORAL - Precio: $1.90 ",
    "SCREEN FINGERTIPS - Precio: $0.45",
    "SUPER COMBO BLANQUEADOR - Precio: $7.90",
    "ONDULADOR TRIPLE - Precio: $10.00",
    "TVBOX ULTIMA VERSION - Precio: $18.40",
    "ASADOR DE CARNE - Precio: $24.00",
    "PORTA CELULAR ADHESIVO - Precio: $1.75 ",
    "HONGO PARLANTE - Precio: $2.95 ",
    "RELOJES MARGARITAS - Precio: $4.95 ",
    "COMBO AFILADOR CUCHILLOS LONCHERA - Precio: $11.75 ",
    "COMBO ROSA PASTEL - Precio: $11.55 ",
    "BIOAQUA MASCARA DE OJOS - Precio: $2.75 ",
    "SET BIOAQUA - Precio: $3.50",
    "COMBO VITAMIN C - Precio: $7.25 ",
    "COMBO GOLD - Precio: $6.50 ",
    "BANDAS PUNTOS NEGROS - Precio: $1.50 A PARTIR DE 3 UNIDADES $1.25 C/U", 
    "PILDORAS VITAMIN C - Precio: $1.75 ",
    "COMBO AGUACATE Y GOLDEN - Precio: $6.35 ",
    "CUATRO LABIALES HUDA - Precio: $2.00",
    "DOCE MASCARILLAS DE COLAGENO - Precio: $7.00",
    "COMBO RODILLO COLAGENOS Y PAPAYA - Precio: $3.75",
    "GEL FACIAL ALOE VERA - Precio: $1.65 ",
    "COMBO MILK - Precio: $6.00",
    "DELINEADORES NAKED - Precio: $1.00",
    "DESODORANTE BLANQUEADOR - Precio: $2.75 ",
    "DESODORANTE Y CREMA BLANQUEADORA - Precio: $3.30",
    "DISPENSADOR DE CEREAL POR UNO - Precio: $7.40 ",
    "COMBO EXTRACTOR FOREVER COLAGENO - Precio: $6.85 ",
    "VEINTICUATRO BROCHAS - Precio: $5.50",
    "MASCARILLA A BASE DE HUEVO - Precio: $2.50 ",
    "BIOAQUA TUBO - Precio: $1.85 ",
    "DESODORANTE PARA CABALLERO - Precio: $2.50 ",
    "MASCARILLAS POR 12 - Precio: $3.90 ",
    "COMBO PAPAYA VITAMINA C - Precio: $7.00",
    "COMBO PRECIOSA - Precio: $7.75 ",
    "COMBO NUDE SOMBRA PEQUENA - Precio: $5.75 ",
    "COMBO SPA - Precio: $4.50",
    "COMBO MASK CARBON TRES PASOS - Precio: $2.75 ",
    "SOMBRA COCOA - Precio: $3.25 ",
    "SOMBRA HUDA - Precio: $2.50 ",
    "PERFUMES - Precio: $7.00",
    "JUEGO DE VAJILLAS - Precio: $23.50",
    "NEON - Precio: $3.00",
    "COSTO DEL ENVIO - Precio: $4.50",
    "COSTO DEL ENVIO - Precio: $5.50",
    "COSTO DEL ENVIO - Precio: $6.50",
    "COSTO DEL ENVIO - Precio: $7.50",
    "COSTO DEL ENVIO - Precio: $8.50",
    "COSTO DEL ENVIO - Precio: $9.50",
    "COSTO DEL ENVIO - Precio: $10.50",
    "COSTO DEL ENVIO - Precio: $11.50",
    "COSTO DEL ENVIO - Precio: $12.50",
    "COSTO DEL ENVIO - Precio: $13.50",
    "COSTO DEL ENVIO - Precio: $14.50",
    "COSTO DEL ENVIO - Precio: $15.50",
    "COSTO DEL ENVIO - Precio: $20.50",
    "MILK FROTHER - Precio: $13.85",
    "SET DE BROCHAS - Precio: $4.95",
    "RELOJ DEPORTIVO PARA CABALLERO - Precio: $4.75",
    "PICATODO NARANJA - Precio: $2.50",
    "CREMA BLANQUEADORA - Precio: $1.25",
    "BATIDORA DE HUEVO - Precio: $1.15",
    "NUEVOS NEONES - Precio: $3.75",
    "COSEDORA PORTATIL - Precio: $1.45",
    "JUGUETE BURBUJA - Precio: $3.45",
    "TACHO CON SENSOR - Precio: $4.95",
    "ALFOMBRA SALDOS - Precio: $15.50",
    "ORGANIZADOR DE ROPA INTERIOR - Precio: $2.95",
    "CORRECTOR DE POSTURA NEGRO - Precio: $2.25",
    "CAMARA TRES ANTENAS - Precio: $14.50",
    "WAFLERA CORAZON - Precio: $12.50",
    "CARPA CASTILLO - Precio: $8.00",
    "VENTILADOR PORTATIL RECARGABLE - Precio: $4.50",
    "TRES EN UNO LUZ VENTILADOR ESPEJO - Precio: $2.25",
    "CUCHARAS Y CEPILLOS FACIALES - Precio: $0.90",																									
    "COLGADOR PARA ZAPATOS  - Precio: $0.95",
    "DISPENSADOR KID - Precio: $9.50",
    "MANTA BRILLANTE NAVIDENA - Precio: $7.50",
    "MESA CON DOS SILLAS  - Precio: $29.50",
    "DESESTRESANTE DE COLORES - Precio: $1.00",
    "SEIS TAPONES - Precio: $1.85",
    "COMBO COCINA - Precio: $13.85",
    "CUCHILLOS ACEITERO TAPAS - Precio: $9.50",
    "CEPILLO Y ONDULADOR RESORTE - Precio: $10.00",
    "PULPO REVERSIBLE - Precio: $1.25",
    "ALFOMBRA YOGA - Precio: $4.25",
    "SARTEN ELECTRICA - Precio: $6.50",
    "SET DE ESPOJAS - Precio: $2.25",
    "MESA LAPTOP INFANTIL - Precio: $7.00",
    "HAPPY NAPPER - Precio: $7.75",
    "ALFOMBRA - Precio: $14.50",
    "LIGAS Y YOGA MAT - Precio: $5.50",
    "DISPENSADOR TOALLAS DE COCINA - Precio: $5.00",
    "NUEVO MASAJEADOR- Precio: $4.50",
    "HAIRCHALK - Precio: $2.75",
    "SOMBRA HUDA PRO - Precio: $9.75",
    "ORGANIZADOR DOS PISOS - Precio: $12.50",
    "BATIDORA AGUJA - Precio: $1.35",
    "MINI SARTENES FORMA DE ANIMALES- Precio: $1.75",
    "RAYADOR CON RECIPIENTE - Precio: $2.50",
    "PULIDOR PEQUENO - Precio: $2.50",
    "SET COSTURERO - Precio: $1.35",
    "SESENTA MASCARILLAS - Precio: $12.00",
    "FORRO TRES PUESTOS - Precio: $9.50",
    "NUEVA MAQUINA DE ALGODON - Precio: $20.75",
    "PANTUFLERA - Precio: $5.50",
    "ELECTRIC BAKING TRAY - Precio: $25.00",
    "TRES FRASCOS DE ACEITERO - Precio: $4.75",
    "ACEITERO CON BROCHA - Precio: $1.90",
    "FLOR QUITA PELUSA - Precio: $0.65",
    "BROCHAS COSMETIC - Precio: $5.75",
    "PELUCHE REFLECTOR - Precio: $7.00",
    "DOCE PLASTILINAS - Precio: $1.65",
    "CEPILLO MULTIUSO RECARGABLE - Precio: $12.00",
    "TRES STEP EN FRASCO - Precio: $2.50",
    "NUEVO ICE ROLLER - Precio: $1.90",
    "LLEVATE TRES CERNIDORAS DE FRUTAS - Precio: $3.75",
    "DOS KESSILER - Precio: $0.90",
    "MESA LAPTOP CON CAJON - Precio: $7.00",
    "PISTOLA BURBUJA - Precio: $2.75 A PARTIR DE 3 UNIDADES $2.50",
    "SMARTWATCH - Precio: $15.50", 
    "COMBO JADE - Precio: $2.25 A PARTIR DE 3 UNIDADES $1.90 C/U", 
    "NUEVA TABLA MAGICA - Precio: $5.50", 
    "FILTROS DISPENSADOR WAFLERA - Precio: $15.00", 
    "EXTENSION DE FOCOS - Precio: $8.50", 
    "ELEFANTE CON MANTA - Precio: $15.50", 
    "AUDIFONOS GAMER - Precio: $13.00", 
    "COMBO FACIAL - Precio: $4.00",
    "AIRPODS - Precio: $3.65", 
    "ROLLO DORADO - Precio: $2.90",
    "SESENTA COLLAGEN DE OJOS - Precio: $2.25 A PARTIR DE 3 UNIDADES $2.00 C/U", 
    "DUO ALOE VERA - Precio: $3.00", 
    "VEINTE COLAGENOS DE LABIOS - Precio: $2.20",
    "SEIS MASKS TRES PASOS EN SOBRE - Precio: $3.50 A PARTIR DE 12 UNIDADES $6.50 C/U",
    "COMBO NEON Y DESESTRESANTE - Precio: $4.25",
    "COMEDERO O BEBEDERO - Precio: $5.25",
    "FAJA PARA HOMBRE - Precio: $4.25",
    "AFEITADORA PARA MASCOTAS - Precio: $11.00",
    "ARGAN MASK PEEL - Precio: $1.65",
    "ZAPATERA MULTIUSO  - Precio: $19.50",
    "PROYECTOR DE LUNA Y ESTRELLAS PARLANTE - Precio: $7.50",
    "PLATERA DOS POZOS - Precio: $27.50",
    "PULL AND JOG PICATODO - Precio: $4.00",
    "PLANCHA VERDE - Precio: $10.50",
    "VARA DESTAPA TUBERIAS - Precio: $0.85",
    "CORTINA LUZ DE HADA - Precio: $5.00",
    "AFEITADORA PARA MASCOTAS - Precio: $10.25",
    "ALFOMBRA DOS METROS - Precio: $18.00",
    "ORGANIZADOR GIRATORIO - Precio: $4.50",
    "RAYADOR CON PALANCA - Precio: $7.00",
    "OLLA RAYADORA - Precio: $3.75",
    "ALFOMBRA PARA COCINA - Precio: $6.50",
    "FORRO DE AUTO - Precio: $11.50",
    "GUANTES DE ENTRENAMIENTO - Precio: $2.25",
    "COMBO EXERCISE - Precio: $10.25",
    "MINI ARO DE LUZ - Precio: $0.75",
    "TRES COLGADORES MULTIUSO - Precio: $1.30",
    "CAJA DE PARCHES - Precio: $1.00",
    "ESCRITORIO PORTATIL - Precio: $21.00",
    "LUCES ESTRELLA Y CORTINA - Precio: $14.50",
    "CAJA DE DIEZ MASCARILLAS - Precio: $2.00",
    "PORTA ROPA INTERIOR - Precio: $1.75",
    "SET COCINA - Precio: $4.50",
    "APARADOR MEDIANO PARA BANO - Precio: $5.50",
    "NUEVO SET DE PLASTILINA - Precio: $4.00",
    "JUEGO DIDACTICO - Precio: $5.95",
    "PARCHE PARA OJOS - Precio: $0.90",
    "COSEDORA GRANDE - Precio: $3.00",
    "TENDEDERO DE ROPA TRES EN UNO - Precio: $5.95",
    "LIMPIA MALLAS - Precio: $1.80",
    "TINA PARA PIES - Precio: $7.50",
    "JABONERA HOJA - Precio: $0.85",
    "SEIS JABONERAS HOJAS - Precio: $4.40",
    "VENTILADOR DE LAPTOP - Precio: $4.75",
    "ACEITERO GRANDE - Precio: $1.90",
    "HIELERA - Precio: $1.60",
    "COMBO PARA ELLOS - Precio: $7.75",
    "COMBO FLAMINGO - Precio: $12.75",
    "ESCURRIDOR DE PLATOS - Precio: $2.40",
    "ASADOR ELECTRICO - Precio: $17.50",
    "EJERCITADOR PARA CINTURA Y ABDOMEN - Precio: $3.95",
    "BANDEJA ESCURRIDORA - Precio: $1.35",
    "PALITOS DESTAPA TUBERIAS - Precio: $0.50 A PARTIR DE 6 UNIDADES $0.45 C/U",
    "CANON DE AGUA - Precio: $3.75",
    "DOS EN UNO SARTEN Y ASADOR - Precio: $11.50",
    "MAQUINA PARA BROWNIES - Precio: $14.50",
    "DECOMPRESSION TOY - Precio: $3.50",
    "LUCES ESTRELLAS - Precio: $8.50",
    "ARBOL Y ALFOMBRA - Precio: $46.00",
    "PROTECTOR PARA RABRISAS - Precio: $5.50",
    "MASAJEADOR PARA AUTO - Precio: $9.00",
    "SERVILLETERO Y PORTA CELULAR - Precio: $3.85",
    "NUEVOS AUDIFONOS GAMER - Precio: $10.25",
    "NUEVO SMARTWATCH- Precio: $18.25",
    "DEDALES GAMER - Precio: $0.45",
    "RELOJ INTELIGENTE T PLUS - Precio: $14.95",
    "PAILA PARA HACER HELADO - Precio: $4.75",
    "NUEVA BALANZA - Precio: $7.00",
    "MESA PORTATIL - Precio: $14.50",
    "COMBO BRAZILIAN - Precio: $11.40",
    "COMBO MIOMI - Precio: $13.45",
    "DOCE PESTANAS - Precio: $7.50",
    "NUEVO WHITENING COMBO - Precio: $4.95",
    "COMBO ANGIE - Precio: $8.45",
    "DELINEADOR Y PESTANAS - Precio: $1.75",
    "DELINEADOR SOMBRA Y PESTANAS - Precio: $4.00",
    "COMBITO FACIAL - Precio: $3.10",
    "MESA PORTATIL - Precio: $14.50",
    "DOCE MASCARILLAS BIOAQUA - Precio: $3.50",
    "RASURADORA INTELIGENTE - Precio: $3.75",
    "CINCO FILTROS ADAPTADORES - Precio: $2.75",
    "BRA CON PASADORES - Precio: $1.65",
    "DOS ICECUBE MAKER - Precio: $0.95",
    "JABON Y CREMA BLANQUEADORES - Precio: $2.30",
    "EXTENSION ELECTRICA - Precio: $3.50",
    "DOS COLGADORES EN UNO - Precio: $18.25",
    "ONDULADOR NOVA Y PLANCHA - Precio: $12.50",
    "CUATRO SOPORTES PARA LAVADORA - Precio: $2.30",
    "CAMARA CINCO ANTENAS - Precio: $14.00",
    "PROTECTOR DE VIDRIO - Precio: $5.00",
    "PULIDOR DE UNAS GRANDE - Precio: $10.25",
    "ZOOVA - Precio: $5.95",
    "TRES FLORES - Precio: $1.50",
    "LUNA HUMIFICADORA - Precio: $6.75",
    "HUMIFICADOR CILINDRICO - Precio: $4.25",
    "NUEVA ZAPATERA - Precio: $12.50 A PARTIR DE 3 UNIDADES $12.10 C/U",
    "CAMARA DIGITAL - Precio: $6.35",
    "ORGANIZADOR DE CRISTAL GIRATORIO - Precio: $8.50",
    "SET DE DIEZ OCHO PLASTULINAS - Precio: $2.25",
    "SET DOS DE DOCE PLASTILINAS - Precio: $1.75",
    "SET DOS DE DIEZ OCHO PLASTILINAS - Precio: $3.00",
    "MOSQUITERO - Precio: $4.95",
    "AMPLIFICADOR - Precio: $2.10",
    "ARBOL CON PINA - Precio: $44.00",
    "COMBO DENISE - Precio: $7.95",
    "TOLDO DOS PLAZAS - Precio: $9.25 A PARTIR DE 3 UNIDADES $9.00 C/U",
    "CARPA TOLDO OTROS COLORES - Precio: $15.50",
    "MINI ZAPATERA - Precio: $5.40",
    "LUCES DIEZ METROS - Precio: $6.50",
    "LONCHERA ELECTRICA - Precio: $5.40",
    "VENTILADOR DE LAPTOP - Precio: $4.05",
    "PICATODO NARANJA - Precio: $2.40",
    "MAQUINA LIMPIA BROCHAS - Precio: $3.75",
    "ARDILLA ANTIESTRES - Precio: $0.95",
    "TORRE DE LUZ - Precio: $4.50",
    "AMBIENTADOR PARA AUTO - Precio: $0.75",
    "REPISA PLEGABLE - Precio: $1.95",
    "GANCHO MULTIUSO - Precio: $0.95",
    "SET DE CUCHILLOS - Precio: $7.00",
    "ALFOMBRAS UNO OCHENTA - Precio: $6.50",
    "ARBOL Y LUCES MULTICOLOR - Precio: $46.00",
    "ALFOMBRA REDONDA - Precio: $5.00",
    "SET DE CUCHARONES - Precio: $4.25",
    "MINI AIRE - Precio: $6.95",
    "ULTRA SONIC NEBULIZER - Precio: $8.75",
    "PROMO ALFOMBRA UNO OCHENTA - Precio: $5.00",
    "PROMO SETENTA Y CINCO TARJETAS - Precio: $1.00",
    "PROMO MAQUINA PARA MASCARILLAS - Precio: $14.50",
    "PROMO OCHO ESTRELLAS - Precio: $0.60",
    "PROMO VASOS PORTABLES - Precio: $1.05",
    "PROMO PLATERA LIMPIA OLLA Y ESCURRIDOR - Precio: $6.95",
    "PROMO LUCES MULTICOLOR DOS POR DOS - Precio: $4.95",
    "PROMO FOREVER Y CEPILLO - Precio: $8.00",
    "PROMO ALFOMBRA UNO OCHENTA - Precio: $5.00",
    "PROMO SETENTA Y CINCO TARJETAS - Precio: $1.00",
    "PROMO MAQUINA PARA MASCARILLAS - Precio: $14.50",
    "PROMO RED OCHO ESTRELLAS - Precio: $0.60",
    "PROMO VASOS PORTABLES - Precio: $1.05",
    "PROMO LONCHERA CON PLASTILINAS - Precio: $3.85",
    "PROMO PLATERA LIMPIA OLLA Y ESCURRIDOR - Precio: $6.95",
    "PROMO LUCES MULTICOLOR DOS POR DOS - Precio: $4.95",
    "PROMO FOREVER Y CEPILLO - Precio: $8.00",
    "PROMO HAPPY NAPPER - Precio: $6.95",
    "PROMO TREINTA MASCARILLAS - Precio: $4.50",
    "PROMO PELOTA MAT Y BANDAS - Precio: $10.25",
    "PROMO WAFLERA SARTEN Y BATIDORA - Precio: $15.40",
    "PROMO MANTA Y ELEFANTE - Precio: $14.95",
    "PROMO ZAPATERA DOS CUERPOS - Precio: $12.50",
    "PROMO RED PISTOLA DE BURBUJAS - Precio: $1.95",
    "PROMO PULPO - Precio: $0.95",
    "PROMO LENTES DE CONTACTO - Precio: $5.30",
    "PROMO RED JUEGO DE CUCHILLOS - Precio: $5.95",
    "PROMO INFLADOR - Precio: $11.00",
    "PROMO MOLINO - Precio: $7.25",
    "PROMO CARPA TUNEL - Precio: $15.45",
    "PROMO RED BLUSA TERMICA - Precio: $2.75",
    "PROMO LABIALES HUDA - Precio: $4.50",
    "PROMO ALFOMBRA VARIAS - Precio: $4.45",
    "PROMO CREPERA - Precio: $12.75",
    "PROMO MINI LAVADORA - Precio: $2.20",
    "PROMO ALCANCIA UNICORNIO - Precio: $4.75",
    "PROMO SECADOR MASCOTAS - Precio: $8.00",
    "PROMO BLUSA TERMICA - Precio: $2.75",
    "PROMO MASAJEADOR FACIAL - Precio: $4.90",
    "PROMO MASAJEADOR FACIAL - Precio: $4.95",
    "PROMO CEPILLO Y ONDULADOR - Precio: $9.75",
    "PROMO PORTA ROPA INTERIOR - Precio: $1.60",
    "PROMO PARRILLA - Precio: $8.75",
    "PROMO HAIRCHALK - Precio: $2.50",
    "PROMO BROCHAS MULTI COSMETIC - Precio: $6.50",
    "PROMO COMBO BLANQUEADOR - Precio: $6.65",
    "PROMO CEPILLO MULTIUSO - Precio: $11.40",
    "PROMO COMBO CELESTE - Precio: $4.25",
    "PROMO CINTILLO Y COLAGENOS - Precio: $3.35",
    "PROMO CORRECTOR DE ESPALDA - Precio: $2.20",
    "PROMO RED ABRIGO PELUCHE - Precio: $5.25",
    "PROMO RED ALGODON MAQUINA - Precio: $17.25",
    "PROMO RED GORRO - Precio: $0.95",
    "PROMO RED OSO REFLECTOR - Precio: $6.95",
    "PROMO RED SHOE RACK - Precio: $5.80",
    "PROMO RED OLLA DE CERA - Precio: $6.25",
    "PROMO RED COMBO PUNTOS NEGROS - Precio: $6.20",
    "PROMO RED LUCES HADA - Precio: $4.50",
    "PROMO RED APARADOR DE BANO - Precio: $11.95",
    "PROMO RED DISPENSADOR DE BOLSA - Precio: $1.95",
    "PROMO RED FACE SHIELD - Precio: $0.90",
    "PROMO RED JADE - Precio: $1.75",
    "PROMO RED ROPERO DOS CUERPOS - Precio: $12.50",
    "PROMO RED BANDAS - Precio: $3.00",
    "PROMO RED GORRO - Precio: $0.95",
    "PROMO RED CEPILLO Y PLANCHA - Precio: $15.25",
    "PROMO RED INFLADOR - Precio: $11.00",
    "PROMO RED ORGANIZADOR DOS PISOS - Precio: $12.95",
    "PROMO RED SALIDAS DE BANO - Precio: $5.50",
    "PROMO RED COMBO MOLINO ACEITERO - Precio: $9.15",
    "PROMO RED COMBO CARBON - Precio: $2.55",
    "PROMO RED COMNO ORGA LIMPIA - Precio: $12.75",
    "PROMO RED COMBO HUEVERA FILTROS - Precio: $7.85",
    "PROMO RED LUCES ESTRELLAS - Precio: $6.95",
    "PROMO RED WAFLERA - Precio: $8.80",
    "PROMO RED ALFOMBRA UNO OCHENTA - Precio: $4.25",
    "PROMO RED PORTA CEPILLOS - Precio: $0.80",
    "PROMO RED COSEDORA GRANDE - Precio: $2.50",
    "PROMO RED MUNECA TENSIOMETRO - Precio: $7.95",
    "MASAJEADOR DHL - Precio: $9.50",
    "ASPIRADORA MANUAL - Precio: $5.30",
    "SPRAY ANTI RAYONES- Precio: $4.75",
    "RELOJ T QUINIENTOS - Precio: $12.00",
    "RELOJ HIWATCH - Precio: $16.00",
    "MESA PORTATIL CON VENTILADOR - Precio: $8.25 A PARTIR DE 3 UNIDADES $8.00 C/U",
    "NUEVO MASAJEADOR PARA AUTO - Precio: $12.00",
    "CAMARA DE BURBUJAS - Precio: $4.50",
    "SET RAYADOR - Precio: $4.95",
    "ROBOT BARREDOR - Precio: $12.00",
    "ASIENTO AZUL - Precio: $4.50",
    "PULPO ACUATICO- Precio: $6.25",
    "PROMO RED PLATERA UN POZO - Precio: $21.50",
    "PROMO RED BATIDORA - Precio: $5.50",
    "PROMO RED TACHO LIMPIA OLLA Y ESTRELLAS - Precio: $8.75",
    "PROMO RED ALFOMBRAS SALDOS - Precio: $10.00",
    "ALFOMBRAS DOS METROS - Precio: $18.00",
    "MANTA DOS METROS - Precio: $12.00",
    "VENTILADORES DE COLORES - Precio: $4.50",
    "COMBO CABALLERO - Precio: $11.25",
    "LAMPARITA REFLECTORA - Precio: $4.75",
    "COMBO CANGURO - Precio: $9.50",
    "ALCANCIA CAMION - Precio: $14.00",
    "JUEGO DE DADOS - Precio: $7.25",
    "MEDIANO INFLADOR DE LLANTAS - Precio: $3.95",
    "COMBO RELOJ PERFUME Y CINTURON - Precio: $8.50",
    "COLGADOR PLATEADO Y NEGRO - Precio: $9.25",
    "LAMPARA PARA UNAS - Precio: $4.95",
    "PORTA BRASIER - Precio: $1.75",
    "PARLANTE DE COLORES - Precio: $4.50",
    "PLASTILINA - Precio: $2.25",
    "RELOJ DE PARED - Precio: $4.50",
    "COMBO DE MAQUILLAJE - Precio: $6.75",
    "ALUMINIO ADHESIVO - Precio: $2.50",
    "SARTEN CUATRO EN UNO - Precio: $6.75",
    "PROMO RED PLANCHA SONAR - Precio: $8.75",
    "PROMO RED GIRATORIO - Precio: $7.90",
    "PROMO RED LIMPIA BROCHAS - Precio: $3.40",
    "PROMO RED TECLADO - Precio: $3.50",
    "PROMO RED FORRO TRES PUESTOS - Precio: $8.95",
    "PROMO RED HAPPY NAPPER - Precio: $6.95",
    "PROMO RED ARO DE LUZ - Precio: $7.75",
    "PROMO RED FOCO CAMARA - Precio: $12.95",
    "PROMO RED BROCHAS - Precio: $4.50",
    "PROMO RED ALFOMBRAS - Precio: $13.45",
    "PROMO RED MESA LAPTOP - Precio: $5.25",
    "PROMO RED JUEGO DE ALFOMBRA - Precio: $6.00",
    "PROMO RED EXFO Y FOREVER - Precio: $4.50",
    "PROMO RED COMBO NUDE - Precio: $8.90",
    "PROMO RED TREINTA MASCARILLAS - Precio: $4.60",
    "PROMO RED ASPIRADORA - Precio: $5.75",
    "PROMO RED NOVA Y SONAR - Precio: $12.25",
    "PROMO RED CEPILLO Y PLANCHA - Precio: $15.00",
    "PROMO RED CEPILLO Y FOROVER - Precio: $8.00",
    "PROMO RED NOVA Y CEPILLO - Precio: $10.00",
    "PROMO RED CANGUILERA - Precio: $10.00",
    "PROMO RED MASAJEADOR - Precio: $8.50",
    "PROMO RED FRELOJERA - Precio: $10.50",
    "PROMO RED CAMARA CON ANTENAS - Precio: $13.95",
    "PROMO RED YOGA MAT - Precio: $3.95",
    "PROMO RED AUDIFONOS GAMER - Precio: $9.75",
    "PROMO RED LUCES ESTRELLAS - Precio: $6.45",
    "PROMO RED ALMOHADA - Precio: $3.25",
    "PROMO RED MASAJEADOR FACIAL - Precio: $4.25",
    "PROMO RED COLGADOR DE ROPA - Precio: $9.00",
    "PROMO RED AFILADOR - Precio: $1.95",
    "PROMO RED CORRECTOR DE ESPALDA - Precio: $2.75",
    "PROMO RED MANTA BRILLANTE - Precio: $10.50",
    "PROMO RED REPISA OCULTA - Precio: $8.75",
    "PROMO RED ALUMINIO - Precio: $0.90",
    "PROMO RED ROPERO TRES CUERPOS - Precio: $18.95",
    "PROMO RED CINCO SARTENES - Precio: $5.95",
    "PROMO RED PLANCHA VERDE - Precio: $9.95",
    "PROMO RED SET DE ESPONJA - Precio: $1.90",
    "PROMO RED COMBO DEPILATE - Precio: $9.75",
    "PROMO RED MINI IMPRESORA - Precio: $14.75",
];