let options = [

    "VISOR TRANSPARENTE - Precio: $0.15",
    "SET PUNTOS NEGROS - Precio: $5.60", 
    "DESODORANTE ACLARADOR - Precio: $2.75",
    "ORGANIZADOR DE BANO - Precio: $12.50",
    "HDMI - Precio: $4.00",
    "PORTA PLATOS - Precio: $3.95 ",
    "ARO DE LUZ - Precio: $8.50 ",
    "SET ONDAS - Precio: $10.50 ",
    "INFLADOR DE PELOTAS Y PISCINA - Precio: $1.10",
    "LUNA MINI FOREVER - Precio: $1.75",
    "ONDULADOR NOVA - Precio: $3.70 ",
    "CEPILLO SECADORA DE PERRO - Precio: $8.50",
    "SALIDAS DE BANO Y GORRO - Precio: $6.00",
    "CAJON OCULTO - Precio: $0.95 ",
    "FOCO PARLANTE GRANDE - Precio: $10.50 ",
    "SET SALUD INFANTIL - Precio: $3.00",
    "MESITA PARA TV - Precio: $2.50 ",
    "ORGANIZADOR DE SALSAS - Precio: $4.00",
    "SET DE LIGAS DE CINCO - Precio: $1.75 ",
    "COMBO PASTELERO - Precio: $11.75 ",
    "PORTA TAZAS MEDIANO - Precio: $1.05 ",
    "SEIS GUANTES DE OLLA - Precio: $2.90 ",
    "SOPORTE DE TV - Precio: $2.90 ",
    "LIMPIA OLLA - Precio: $1.15",
    "LIGAS DE HOMBRE - Precio: $3.95",
    "ALCANCIA POLICIA - Precio: $14.00",
    "KIT EJERCITATE - Precio: $10.25",
    "ROPERO TRES CUERPOS - Precio: $19.25 ",
    "DISPENSADOR DE JABON MASCOTAS - Precio: $1.50 ",
    "PLATERA COLORES - Precio: $11.75",
    "ATRAPA PELUZAS - Precio: $3.40 ",
    "ESCURRIDOR DE FRUTAS - Precio: $2.00",
    "INFLADOR DE LLANTAS - Precio: $8.00",
    "SPRAY DE ACEITE - Precio: $1.50 ",
    "OLLA DE CERA - Precio: $6.75 ",
    "SET BLANQUEADOR COMPLETO - Precio: $3.25",
    "SET CINTILLO Y RODILLO FACIAL - Precio: $2.75 ",
    "DOCE COLAGENO DE LABIOS - Precio: $2.20",
    "TENDEDERO DE ROPA - Precio: $13.75 ",
    "JABONERA COLORES - Precio: $0.75 ",
    "HUMIFICADOR FLORERO - Precio: $4.50",
    "TAPETE PARA AMASAR - Precio: $1.20",
    "LIMPIA VIDRIO - Precio: $0.95 ",
    "CAMARA IP - Precio: $23.50 ",
    "PORTA CUCHARONES - Precio: $1.00",
    "ICE ROLLER - Precio: $2.75 ",
    "SEIS MASKS TRES PASOS EN SOBRE - Precio: $3.75 ",
    "FLEX TAPE - Precio: $1.00",
    "SEIS TOALLAS DE COCINA - Precio: $2.75 ",
    "DESTAPA CORCHO - Precio: $6.75",
    "TRAPEADOR PORTATIL - Precio: $4.00",
    "INFLADOR DE GLOBOS - Precio: $12.00",
    "COMBO HOGAR LIMPIO - Precio: $7.90 ",
    "REPISA MULTIUSO - Precio: $5.50 ",
    "TIRA LED GRANDE - Precio: $6.50 ",
    "TIRA LED PEQUENA - Precio: $3.75 ",
    "MOLDES DE TORTA - Precio: $6.25 ",
    "ESQUINERO DE BANO - Precio: $10.00 ",
    "MAQUINA PARA YOGURT - Precio: $4.95 ",
    "CAJA DE 10 MASCARILLAS FACIALES - Precio: $3.00",
    "ROPERO DOS CUERPOS - Precio: $13.00 ",
    "SEIS ESTRELLAS DE COCINA - Precio: $3.00 ",
    "CAJA DE DESINFECCION - Precio: $4.75 ",
    "DISPENSADOR DE CEREAL POR DOS - Precio: $12.50 ",
    "MASAJEADOR CORPORAL - Precio: $4.25 ",
    "JUEGO DE CEVICHERAS - Precio: $3.75 ",
    "TECLADO - Precio: $3.65",
    "ARO DE LUZ DIEZ PULGADAS - Precio: $12.50 ",
    "CEPILLO Y EXTRACTOR DE PUNTOS - Precio: $10.75 ",
    "ARO DE LUZ Y CEPILLO - Precio: $14.75 ",
    "DISPENSADOR DE AGUA - Precio: $2.75 ",
    "PAR DE GUANTES - Precio: $1.50 ",
    "LAMINAS LIMPIADORAS - Precio: $1.25 ",
    "PELOTA YOGA - Precio: $4.95 ",
    "TENSIOMETRO DE MUNECA - Precio: $7.90 ",
    "ESPONJA SILICON - Precio: $1.20 ",
    "FOCO ESPEJO - Precio: $4.25 ",
    "FOCO CAMARA - Precio: $12.95 ",
    "COLGADOR DE ROPA - Precio: $9.50 ",
    "SILICONE PARA LIMPIAR BANO - Precio: $1.45",
    "MICROFONO - Precio: $3.95 ",
    "LICUADORA - Precio: $4.25 ",
    "DOCE COLAGENOS DE OJOS - Precio: $2.20",
    "TREINTA TARJETAS VIRUS - Precio: $1.00",
    "ESFERA ARO - Precio: $5.50",
    "SOSTENEDOR DE PUERTA - Precio: $2.00",
    "SEIS MASCARILLAS BIOAQUA - Precio: $2.30",
    "CORRECTOR DE ESPALDA - Precio: $3.00",
    "PROYECTOR - Precio: $2.75 ",
    "SERUM VITAMIN C - Precio: $1.80 ",
    "KIT TRES PASOS BIOAQUA - Precio: $2.80 ",
    "COLGADOR PARA PUERTAS - Precio: $2.50 ",
    "VENTILADOR - Precio: $6.95 ",
    "PUSH UP BRA - Precio: $1.25 ",
    "CAJA DE HERRAMIENTA - Precio: $3.75 ",
    "ALFOMBRAS INFANTILES SUBLIMADAS - Precio: $17.50 ",
    "CINTURON PARA CABALLERO - Precio: $4.50 ",
    "PULIDOR DE UNAS GRANDE - Precio: $10.00",
    "ORGANIZADOR CUADRADO - Precio: $4.40 ",
    "FOCO PARLANTE - Precio: $3.65 A PARTIR DE 3 UNIDADES $3.50 C/U",
    "BANDA DE BRASIER - Precio: $1.45 ",
    "TENDEDERO REDONDO - Precio: $10.00",
    "DISPENSADOR DE GASEOSAS - Precio: $2.10 ",
    "CHOCOLATERA - Precio: $8.50",
    "MAQUINA DE PUNTOS NEGROS - Precio: $4.00 ",
    "BOTITAS PARA PERRO - Precio: $2.20 ",
    "CARPA TUNEL - Precio: $16.50 A PARTIR DE 3 UNIDADES $16.00 C/U ",
    "PESAS - Precio: $42.00",
    "TREINTA TARJETAS VIRUS KID - Precio: $1.00 ",
    "BLUSA TERMICA - Precio: $3.25 ",
    "RELOJ REPELENTE - Precio: $0.65 A PARTIR DE 12 UNIDADES $0.60 C/U",
    "TRAPEADOR PORTATIL - Precio: $3.50 ",
    "HUEVERA - Precio: $1.25",
    "PORTA ESPONJA - Precio: $0.50 ",
    "LUCES TRES METROS - Precio: $8.50 ",
    "TRES COLGADORES DE NUBES - Precio: $1.15 ",
    "PORTA CELULAR - Precio: $0.65 ",
    "MINI IMPRESORA - Precio: $16.50 ",
    "COMBO ACLARADOR - Precio: $4.50 ",
    "MANGUERA - Precio: $6.75",
    "PORTA LAPIZ Y CELULAR - Precio: $3.25 ",
    "CINTA DOBLE CARA - Precio: $1.00",
    "CANGUROS MICKEY - Precio: $4.00",
    "ORGANIZADOR TRES PISOS - Precio: $13.50 ",
    "MESA LAPTOP - Precio: $5.75 ",
    "MAQUINA MASAJES REDUCTORES - Precio: $12.00",
    "RUEDA ABDOMINAL - Precio: $3.50 ",
    "PARRILLA RECTANGULAR - Precio: $9.25",
    "TREINTA FUNDAS DESINFECTANTES - Precio: $2.10 ",
    "DOCE CINTILLOS - Precio: $7.50 ",
    "BALANZA - Precio: $7.25 ",
    "NEUBOLIZADOR - Precio: $9.25 ",
    "PAR DE MEDIAS - Precio: $1.75 ",
    "CEPILLO CON DISPENSADOR - Precio: $1.45",
    "VASOS PORTATILES - Precio: $1.20 ",
    "SPINNER - Precio: $0.95 A PARTIR DE 3 UNIDADES $0.85 C/U",
    "ESCURRIDOR DE ESPONJA - Precio: $1.45 ",
    "SEIS FILTROS ADAPTADORES - Precio: $3.50 ",
    "TALADRO - Precio: $11.50 ",
    "TRIPODE - Precio: $1.25 ",
    "PELUCHE MANTA - Precio: $7.50 ",
    "CUERDA DIGITAL - Precio: $2.75 ",
    "SACA ESCAMAS - Precio: $0.70 ",
    "CANGUILERA - Precio: $11.25 ",
    "BLANQUADOR DE DIENTES - Precio: $2.00",
    "CEPILLO DE DUCHA - Precio: $0.80 ",
    "UNICORNIO CON MANTA - Precio: $11.75 ",
    "LENTES DE CONTACTO - Precio: $7.50 ",
    "FREIDORA - Precio: $44.00",
    "ESTRELLAS DESENREDANTES - Precio: $0.55 ",
    "SET DE CUBIERTOS - Precio: $17.50 ",
    "OXIMETRO - Precio: $3.50 ",
    "ABLANDADOR DE CARNES - Precio: $1.25 ",
    "GORRO DE BANO - Precio: $0.90 A PARTIR DE 6 UNIDADES $0.85",
    "BOLSA PARA LAVAR BRASIER - Precio: $1.00",
    "MASAJEADOR FACIAL DE VIDRIO - Precio: $5.25",
    "ALUMINIO PARA HORNILLAS - Precio: $1.75",
    "SET SALUD - Precio: $12.75 ",
    "CEPILLO SECADOR - Precio: $6.50",
    "DOCE PASTILLAS PARA BANO - Precio: $0.80 ",
    "CARPA TOLDO CELESTE - Precio: $13.50 ",
    "MAGIC PACK - Precio: $3.50 ",
    "FOCO TRES ALAS - Precio: $3.40 ",
    "MAQUINA DE ALGODON DE AZUCAR - Precio: $18.50 ",
    "PISTOLA BURBUJA - Precio: $2.75 ",
    "TIRA DE SILICON PARA DUCHA - Precio: $1.25 ",
    "ESFERA PROYECTORA - Precio: $4.50 ",
    "JUEGO DE CUCHILLOS - Precio: $7.50 ",
    "TOMATODOS - Precio: $2.75 ",
    "TOLDO REDONDO DOS PLAZAS - Precio: $9.50 ",
    "DISPENSADOR DE PASTA UV - Precio: $4.75 ",
    "SET DE TRES SERUMS - Precio: $3.75 ",
    "HUMIFICADOR COCO - Precio: $4.75",
    "MAQUINA PINTURA - Precio: $20.50 ",
    "DISPENSADOR DE GRANOS UN COMPARTIMIENTO - Precio: $2.95 ",
    "ROLLO DE ALUMINIO TRES METROS - Precio: $1.90 ",
    "SEPARADOR DE LLEMA - Precio: $0.20 ",
    "SESENTA COLAGENOS DE LABIOS - Precio: $2.20",
    "CERCA DE HOJAS - Precio: $7.60",
    "VISOR ACRILICO - Precio: $0.95 ",
    "KID DE CEJAS - Precio: $2.00",
    "COMBO MORENA - Precio: $7.25 ",
    "ARBOL DE NAVIDAD - Precio: $36.00",
    "LONCHERA ELECTRICA - Precio: $4.75 ",
    "COMBO COLAGENO - Precio: $8.80 ",
    "SEIS LABIALES MAGICO - Precio: $3.40 ",
    "PLATERA DE UN POZO - Precio: $22.50 ",
    "TABLA PICAR - Precio: $2.00",
    "ZAPATERA VARIOS COLORES - Precio: $13.25 ",
    "ORGANIZADOR DE CONDIMENTOS - Precio: $8.50 ",
    "AFILADOR DE CUCHILLOS - Precio: $2.05 ",
    "LIGAS DE RESISTENCIA - Precio: $3.25 ",
    "ALCANCIA DIGITAL - Precio: $4.50 ",
    "MOLINO DE CARNE - Precio: $7.25",
    "MAQUINA DE COSER - Precio: $8.50 ",
    "SET INFANTIL - Precio: $13.75 ",
    "PELUCHE ABRIGO - Precio: $6.50 ",
    "ORGANIZADOR OCULTO - Precio: $9.50 ",
    "SARTEN DE HUEVO - Precio: $1.25 ",
    "ASPIRADORA DE AUTO - Precio: $6.25 ",
    "SACA CALLO - Precio: $2.45",
    "BATIDORA - Precio: $5.75 ",
    "GAFAS WIFI - Precio: $6.75 ",
    "PICATODO ELECTRICO - Precio: $10.50 ",
    "GREEN MASK - Precio: $1.40 ",
    "ELEFANTE MUSICAL - Precio: $8.50 ",
    "MAQUINA LIMPIA BROCHAS - Precio: $0.80 ",
    "BANDEJAS DE REFRIGERADOR - Precio: $0.80 ",
    "DESTAPA TUBERIAS - Precio: $0.65 ",
    "AZUCARERA - Precio: $3.50 ",
    "REFRIGERADOR - Precio: $25.80 ",
    "KIT DEPILACION Y ROSTRO - Precio: $10.50 ",
    "COMBO ROSTRO LINDO - Precio: $3.50 ",
    "COMBO MADI - Precio: $13.00 ",
    "CIGARILLOS - Precio: $1.50 ",
    "KIT PUNTOS NEGROS - Precio: $6.85 ",
    "TENSIOMETRO - Precio: $9.50 ",
    "CREMA Y SPLASH - Precio: $3.50 ",
    "COMBO DANIELA - Precio: $11.75 ",
    "MINI LAVADORA - Precio: $2.50 ",
    "SEIS TAPAS DE SILICON - Precio: $1.00",
    "CUCHILLOS Y MOLINO - Precio: $14.50 ",
    "PLANCHA BABOYIESS - Precio: $10.75 ",
    "PLANCHA NEGRA - Precio: $5.75 ",
    "DUO PERFECTO - Precio: $12.00",
    "ALMOHADA - Precio: $3.50 ",
    "COMBO BELLEZA - Precio: $18.50 ",
    "CEPILLO Y FOREVER - Precio: $8.25",
    "COMBO COLAGENO Y FOREVER - Precio: $4.35 ",
    "ARO Y FOREVER - Precio: $9.75",
    "COMBO NUDE - Precio: $10.75 ",
    "COMBO GABRIELA - Precio: $12.75 ",
    "PESTANAS - Precio: $2.00",
    "AFILADOR ARCO - Precio: $1.95 ",
    "ASPIRADORA DE CARRO TIPO DOS - Precio: $6.50 ",
    "FOCO PARLANTE TRES ALAS - Precio: $9.50 ",
    "COLGADOR TOTALMENTE METALICO - Precio: $6.50 ",
    "UNA HORNILLA - Precio: $6.00",
    "WAFLERA - Precio: $12.00 A PARTIR DE 3 UNIDADES $11.50 C/U",
    "MAQUINA MASCARA - Precio: $21.00",
    "CREPERA - Precio: $13.50 ",
    "SACA PELUZA - Precio: $2.25 ",
    "MICKEY O MINIE - Precio: $16.50 ",
    "TACHO CON MOPA - Precio: $7.50 ",
    "FOCO PARLANTE - Precio: $3.90 ",
    "DISPENSADOR DE FUNDAS - Precio: $2.20",
    "HUEVERA ELECTRICA - Precio: $4.75 ",
    "ESCURRIDOR DE LEGUMBRES - Precio: $1.45 ",
    "CORRECTOR DE POSTURA CON SENSOR - Precio: $3.00",
    "MINI CAMARA - Precio: $4.25 ",
    "ESTUDIO FOTOGRAFICO - Precio: $4.00",
    "TRAPEADOR CON SPLASH - Precio: $7.75 ",
    "MARTILLO MULTIUSO - Precio: $8.00",
    "LONCHERA CUATRO COMPARTIMIENTOS - Precio: $2.25 ",
    "ADAPTADOR DE LLAVE - Precio: $1.75 ",
    "AUDIFONOS INALAMBRICOS - Precio: $7.75 ",
    "CANDADO CON ALARMA - Precio: $4.95 ",
    "LAVADORA DE ROPA INTERIOR - Precio: $29.00 ",
    "MANTA QUE BRILLA - Precio: $8.25",
    "FORRO PARA MOTO - Precio: $2.95 ",
    "AFEITADORA GOLDEN - Precio: $5.50 ",
    "MANTA PERRITO - Precio: $11.00",
    "MASCARILLA PARA PIES - Precio: $1.25 A PARTIR DE 6 UNIDADES $1.05 C/U",
    "SHOES RACK - Precio: $6.25 ",
    "ELEFANTE - Precio: $5.75 ",
    "SOPORTE DE LAVADORA - Precio: $6.50 ",
    "PASTILLAS PARA LAVADORA - Precio: $0.95 ",
    "SOPORTE PARA CELULAR - Precio: $1.25 ",
    "PIJAMAS PARA DAMAS - Precio: $8.50 ",
    "JUEGO INTERIOR - Precio: $6.50 ",
    "DISPENSADOR DE FREJOL GRANDE - Precio: $11.50 A PARTIR DE 3 UNIDADES $11.00 C/U", 
    "COMBO TITANIUM - Precio: $11.50 ",
    "LABIALES KYLIE - Precio: $4.50 ",
    "LUZ LED SOLAR - Precio: $5.20 ",
    "PLANCHA SONAR - Precio: $9.00",
    "SARTENES CORAZON - Precio: $1.75 ",
    "PASTILLERO - Precio: $3.95",
    "ALFOMBRA UNICORNIO - Precio: $11.50 ",
    "PARLANTE PEQUENO - Precio: $4.75 ",
    "ONDULADOR CEPILLO - Precio: $2.70 ",
    "PARLANTE GRANDE - Precio: $26.50 ",
    "CORTINAS LED - Precio: $8.95 ",
    "LUZ PORTATIL - Precio: $4.00",
    "ORGANIZADOR DE CABLES - Precio: $0.60 ",
    "GUANTE PARA OBJETOS CALIENTES - Precio: $0.45 ",
    "FORRO DE MUEBLE - Precio: $10.50 ",
    "FORRO DE MUEBLE DOS PUESTOS - Precio: $9.50 ",
    "OSO REFLECTOR BLANCO - Precio: $7.00",
    "JABON FACIAL - Precio: $2.25",
    "ESFOLIANTES CORPORALES - Precio: $2.75 A PARTIR DE 3 UNIDADES $2.50 C/U",
    "SEIS EXFO EN GEL - Precio: $3.95",
    "CREMA CORPORAL - Precio: $1.90 ",
    "SCREEN FINGERTIPS - Precio: $0.45",
    "SUPER COMBO BLANQUEADOR - Precio: $7.90",
    "ONDULADOR TRIPLE - Precio: $10.00",
    "TVBOX ULTIMA VERSION - Precio: $18.40",
    "ASADOR DE CARNE - Precio: $25.50",
    "PORTA CELULAR ADHESIVO - Precio: $1.75 ",
    "HONGO PARLANTE - Precio: $2.95 ",
    "RELOJES MARGARITAS - Precio: $4.95 ",
    "COMBO AFILADOR CUCHILLOS LONCHERA - Precio: $11.75 ",
    "COMBO ROSA PASTEL - Precio: $11.55 ",
    "BIOAQUA MASCARA DE OJOS - Precio: $2.75 ",
    "SET BIOAQUA - Precio: $3.50",
    "COMBO VITAMIN C - Precio: $7.25 ",
    "COMBO GOLD - Precio: $6.50 ",
    "BANDAS PUNTOS NEGROS - Precio: $1.50 A PARTIR DE 3 UNIDADES $1.25 C/U", 
    "PILDORAS VITAMIN C - Precio: $1.75 ",
    "COMBO AGUACATE Y GOLDEN - Precio: $6.35 ",
    "CUATRO LABIALES HUDA - Precio: $2.00",
    "DOCE MASCARILLAS DE COLAGENO - Precio: $7.00",
    "COMBO RODILLO COLAGENOS Y PAPAYA - Precio: $3.75",
    "GEL FACIAL ALOE VERA - Precio: $1.65 ",
    "COMBO MILK - Precio: $6.00",
    "DELINEADORES NAKED - Precio: $1.00",
    "DESODORANTE BLANQUEADOR - Precio: $2.75 ",
    "DESODORANTE Y CREMA BLANQUEADORA - Precio: $3.30",
    "DISPENSADOR DE CEREAL POR UNO - Precio: $7.40 ",
    "COMBO EXTRACTOR FOREVER COLAGENO - Precio: $6.85 ",
    "VEINTICUATRO BROCHAS - Precio: $5.50",
    "MASCARILLA A BASE DE HUEVO - Precio: $2.50 ",
    "BIOAQUA TUBO - Precio: $1.85 ",
    "DESODORANTE PARA CABALLERO - Precio: $2.50 ",
    "MASCARILLAS POR 12 - Precio: $3.90 ",
    "COMBO PAPAYA VITAMINA C - Precio: $7.00",
    "COMBO PRECIOSA - Precio: $7.75 ",
    "COMBO NUDE SOMBRA PEQUENA - Precio: $5.75 ",
    "COMBO SPA - Precio: $4.50",
    "COMBO MASK CARBON TRES PASOS - Precio: $2.75 ",
    "SOMBRA COCOA - Precio: $3.25 ",
    "SOMBRA HUDA - Precio: $2.50 ",
    "PERFUMES - Precio: $7.00",
    "JUEGO DE VAJILLAS - Precio: $23.50",
    "NEON - Precio: $3.00",
    "COSTO DEL ENVIO - Precio: $4.50",
    "COSTO DEL ENVIO - Precio: $5.50",
    "COSTO DEL ENVIO - Precio: $6.50",
    "COSTO DEL ENVIO - Precio: $7.50",
    "COSTO DEL ENVIO - Precio: $8.50",
    "COSTO DEL ENVIO - Precio: $9.50",
    "COSTO DEL ENVIO - Precio: $10.50",
    "COSTO DEL ENVIO - Precio: $11.50",
    "COSTO DEL ENVIO - Precio: $12.50",
    "COSTO DEL ENVIO - Precio: $13.50",
    "COSTO DEL ENVIO - Precio: $14.50",
    "COSTO DEL ENVIO - Precio: $15.50",
    "COSTO DEL ENVIO - Precio: $20.50",
    "MILK FROTHER - Precio: $13.85",
    "SET DE BROCHAS - Precio: $4.95",
    "RELOJ DEPORTIVO PARA CABALLERO - Precio: $4.75",
    "PICATODO NARANJA - Precio: $2.50",
    "CREMA BLANQUEADORA - Precio: $1.25",
    "BATIDORA DE HUEVO - Precio: $1.15",
    "NUEVOS NEONES - Precio: $3.75",
    "COSEDORA PORTATIL - Precio: $1.45",
    "JUGUETE BURBUJA - Precio: $3.45",
    "TACHO CON SENSOR - Precio: $4.90",
    "ALFOMBRA SALDOS - Precio: $15.50",
    "ORGANIZADOR DE ROPA INTERIOR - Precio: $2.95",
    "CORRECTOR DE POSTURA NEGRO - Precio: $2.25",
    "CAMARA TRES ANTENAS - Precio: $13.50",
    "WAFLERA CORAZON - Precio: $12.50",
    "CARPA CASTILLO - Precio: $8.00",
    "VENTILADOR PORTATIL RECARGABLE - Precio: $4.50",
    "TRES EN UNO LUZ VENTILADOR ESPEJO - Precio: $2.25",
    "CUCHARAS Y CEPILLOS FACIALES - Precio: $0.90",																									
    "COLGADOR PARA ZAPATOS  - Precio: $0.95",
    "DISPENSADOR KID - Precio: $9.50",
    "MANTA BRILLANTE NAVIDENA - Precio: $7.50",
    "MESA CON DOS SILLAS  - Precio: $29.50",
    "DESESTRESANTE DE COLORES - Precio: $1.00",
    "SEIS TAPONES - Precio: $1.85",
    "COMBO COCINA - Precio: $13.85",
    "CUCHILLOS ACEITERO TAPAS - Precio: $9.50",
    "CEPILLO Y ONDULADOR RESORTE - Precio: $10.00",
    "PULPO REVERSIBLE - Precio: $1.25",
    "ALFOMBRA YOGA - Precio: $4.25",
    "SARTEN ELECTRICA - Precio: $6.50",
    "SET DE ESPOJAS - Precio: $2.25",
    "MESA LAPTOP INFANTIL - Precio: $6.75",
    "HAPPY NAPPER - Precio: $7.45",
    "PESA PARA GRANOS - Precio: $3.15",
    "MINI PLANCHA - Precio: $1.45",
    "FALDA DE ARBOL - Precio: $2.00",
    "MAXPRO - Precio: $21.50",
    "BROCHA Y ACEITERO - Precio: $1.25 A PARTIR DE 3 UNIDADES $1.00 C/U",
    "ALFOMBRA - Precio: $14.50",
    "LIGAS Y YOGA MAT - Precio: $5.50",
    "DISPENSADOR TOALLAS DE COCINA - Precio: $5.00",
    "NUEVO MASAJEADOR- Precio: $4.50",
    "HAIRCHALK - Precio: $2.75",
    "SOMBRA HUDA PRO - Precio: $9.75",
    "ORGANIZADOR DOS PISOS - Precio: $12.50",
    "BATIDORA AGUJA - Precio: $1.35",
    "MINI SARTENES FORMA DE ANIMALES- Precio: $1.75",
    "RAYADOR CON RECIPIENTE - Precio: $2.50",
    "PULIDOR PEQUENO - Precio: $3.75",
    "SET COSTURERO - Precio: $1.35",
    "SESENTA MASCARILLAS - Precio: $12.00",
    "FORRO TRES PUESTOS - Precio: $9.50",
    "NUEVA MAQUINA DE ALGODON - Precio: $20.75",
    "PANTUFLERA - Precio: $5.50",
    "ELECTRIC BAKING TRAY - Precio: $25.00",
    "TRES FRASCOS DE ACEITERO - Precio: $4.75",
    "ACEITERO CON BROCHA - Precio: $1.90",
    "FLOR QUITA PELUSA - Precio: $0.35",
    "BROCHAS COSMETIC - Precio: $5.75",
    "PELUCHE REFLECTOR - Precio: $7.00",
    "DOCE PLASTILINAS - Precio: $1.65",
    "CEPILLO MULTIUSO RECARGABLE - Precio: $12.00",
    "TRES STEP EN FRASCO - Precio: $2.50",
    "NUEVO ICE ROLLER - Precio: $1.90",
    "LLEVATE TRES CERNIDORAS DE FRUTAS - Precio: $3.75",
    "DOS KESSILER - Precio: $0.90",
    "MESA LAPTOP CON CAJON - Precio: $7.00",
    "PISTOLA BURBUJA - Precio: $2.75 A PARTIR DE 3 UNIDADES $2.50",
    "SMARTWATCH - Precio: $15.50", 
    "COMBO JADE - Precio: $2.25 A PARTIR DE 3 UNIDADES $1.90 C/U", 
    "NUEVA TABLA MAGICA - Precio: $5.50", 
    "FILTROS DISPENSADOR WAFLERA - Precio: $15.00", 
    "EXTENSION DE FOCOS - Precio: $9.50", 
    "ELEFANTE CON MANTA - Precio: $15.50", 
    "AUDIFONOS GAMER - Precio: $13.00", 
    "COMBO FACIAL - Precio: $4.00",
    "AIRPODS - Precio: $3.65", 
    "ROLLO DORADO - Precio: $2.90",
    "SESENTA COLLAGEN DE OJOS - Precio: $2.25 A PARTIR DE 3 UNIDADES $2.00 C/U", 
    "DUO ALOE VERA - Precio: $3.00", 
    "VEINTE COLAGENOS DE LABIOS - Precio: $2.20",
    "SEIS MASKS TRES PASOS EN SOBRE - Precio: $3.50 A PARTIR DE 12 UNIDADES $6.50 C/U",
    "COMBO NEON Y DESESTRESANTE - Precio: $4.25",
    "COMEDERO O BEBEDERO - Precio: $5.25",
    "FAJA PARA HOMBRE - Precio: $4.25",
    "AFEITADORA PARA MASCOTAS - Precio: $11.00",
    "ARGAN MASK PEEL - Precio: $1.65",
    "ZAPATERA MULTIUSO  - Precio: $18.95",
    "PROYECTOR DE LUNA Y ESTRELLAS PARLANTE - Precio: $7.50",
    "PLATERA DOS POZOS - Precio: $27.50",
    "PULL AND JOG PICATODO - Precio: $4.00",
    "PLANCHA VERDE - Precio: $10.50",
    "VARA DESTAPA TUBERIAS - Precio: $0.85",
    "CORTINA LUZ DE HADA - Precio: $5.00",
    "AFEITADORA PARA MASCOTAS - Precio: $10.25",
    "ALFOMBRA DOS METROS - Precio: $18.00",
    "ORGANIZADOR GIRATORIO - Precio: $4.50",
    "RAYADOR CON PALANCA - Precio: $7.00",
    "OLLA RAYADORA - Precio: $3.75",
    "ALFOMBRA PARA COCINA - Precio: $6.50",
    "FORRO DE AUTO - Precio: $11.50",
    "GUANTES DE ENTRENAMIENTO - Precio: $2.25",
    "COMBO EXERCISE - Precio: $10.25",
    "MINI ARO DE LUZ - Precio: $0.75",
    "TRES COLGADORES MULTIUSO - Precio: $1.30",
    "CAJA DE PARCHES - Precio: $1.00",
    "ESCRITORIO PORTATIL - Precio: $21.00",
    "LUCES ESTRELLA Y CORTINA - Precio: $14.50",
    "CAJA DE DIEZ MASCARILLAS - Precio: $2.00",
    "PORTA ROPA INTERIOR - Precio: $1.75",
    "SET COCINA - Precio: $4.50",
    "APARADOR MEDIANO PARA BANO - Precio: $5.50",
    "NUEVO SET DE PLASTILINA - Precio: $4.00",
    "JUEGO DIDACTICO - Precio: $5.95",
    "PARCHE PARA OJOS - Precio: $0.90",
    "COSEDORA GRANDE - Precio: $3.00",
    "TENDEDERO DE ROPA TRES EN UNO - Precio: $5.95",
    "LIMPIA MALLAS - Precio: $1.80",
    "TINA PARA PIES - Precio: $7.50",
    "JABONERA HOJA - Precio: $0.85",
    "SEIS JABONERAS HOJAS - Precio: $4.40",
    "VENTILADOR DE LAPTOP - Precio: $4.75",
    "ACEITERO GRANDE - Precio: $1.90",
    "HIELERA - Precio: $1.60",
    "COMBO PARA ELLOS - Precio: $7.75",
    "COMBO FLAMINGO - Precio: $12.75",
    "ESCURRIDOR DE PLATOS - Precio: $2.40",
    "ASADOR ELECTRICO - Precio: $17.50",
    "EJERCITADOR PARA CINTURA Y ABDOMEN - Precio: $3.95",
    "BANDEJA ESCURRIDORA - Precio: $1.35",
    "PALITOS DESTAPA TUBERIAS - Precio: $0.50 A PARTIR DE 6 UNIDADES $0.45 C/U",
    "CANON DE AGUA - Precio: $3.75",
    "DOS EN UNO SARTEN Y ASADOR - Precio: $11.50",
    "MAQUINA PARA BROWNIES - Precio: $14.50",
    "DECOMPRESSION TOY - Precio: $3.50",
    "LUCES ESTRELLAS - Precio: $8.50",
    "ARBOL Y ALFOMBRA - Precio: $46.00",
    "PROTECTOR PARA RABRISAS - Precio: $5.50",
    "MASAJEADOR PARA AUTO - Precio: $9.00",
    "SERVILLETERO Y PORTA CELULAR - Precio: $3.85",
    "NUEVOS AUDIFONOS GAMER - Precio: $10.25",
    "NUEVO SMARTWATCH- Precio: $18.25",
    "DEDALES GAMER - Precio: $0.45",
    "RELOJ INTELIGENTE T PLUS - Precio: $14.95",
    "PAILA PARA HACER HELADO - Precio: $4.75",
    "NUEVA BALANZA - Precio: $7.00",
    "MESA PORTATIL - Precio: $14.50",
    "COMBO BRAZILIAN - Precio: $11.40",
    "COMBO MIOMI - Precio: $13.45",
    "DOCE PESTANAS - Precio: $7.50",
    "NUEVO WHITENING COMBO - Precio: $4.95",
    "COMBO ANGIE - Precio: $8.45",
    "DELINEADOR Y PESTANAS - Precio: $1.75",
    "DELINEADOR SOMBRA Y PESTANAS - Precio: $4.00",
    "COMBITO FACIAL - Precio: $3.10",
    "MESA PORTATIL - Precio: $14.50",
    "DOCE MASCARILLAS BIOAQUA - Precio: $3.50",
    "RASURADORA INTELIGENTE - Precio: $3.75",
    "CINCO FILTROS ADAPTADORES - Precio: $2.75",
    "BRA CON PASADORES - Precio: $1.65",
    "DOS ICECUBE MAKER - Precio: $0.95",
    "JABON Y CREMA BLANQUEADORES - Precio: $2.30",
    "EXTENSION ELECTRICA - Precio: $3.50",
    "DOS COLGADORES EN UNO - Precio: $18.25",
    "ONDULADOR NOVA Y PLANCHA - Precio: $12.50",
    "CUATRO SOPORTES PARA LAVADORA - Precio: $2.30",
    "CAMARA CINCO ANTENAS - Precio: $14.00",
    "PROTECTOR DE VIDRIO - Precio: $5.00",
    "PULIDOR DE UNAS GRANDE - Precio: $10.25",
    "ZOOVA - Precio: $5.95",
    "TRES FLORES - Precio: $1.50",
    "LUNA HUMIFICADORA - Precio: $7.00",
    "HUMIFICADOR CILINDRICO - Precio: $4.25",
    "NUEVA ZAPATERA - Precio: $12.50 A PARTIR DE 3 UNIDADES $12.10 C/U",
    "CAMARA DIGITAL - Precio: $6.35",
    "ORGANIZADOR DE CRISTAL GIRATORIO - Precio: $8.50",
    "SET DE DIEZ OCHO PLASTULINAS - Precio: $2.25",
    "SET DOS DE DOCE PLASTILINAS - Precio: $1.75",
    "SET DOS DE DIEZ OCHO PLASTILINAS - Precio: $3.00",
    "MOSQUITERO - Precio: $4.95",
    "AMPLIFICADOR - Precio: $2.10",
    "ARBOL CON PINA - Precio: $44.00",
    "COMBO DENISE - Precio: $7.95",
    "TOLDO DOS PLAZAS - Precio: $9.25 A PARTIR DE 3 UNIDADES $9.00 C/U",
    "CARPA TOLDO OTROS COLORES - Precio: $15.50",
    "MINI ZAPATERA - Precio: $5.40",
    "LUCES DIEZ METROS - Precio: $9.50",
    "LONCHERA ELECTRICA - Precio: $5.40",
    "VENTILADOR DE LAPTOP - Precio: $4.05",
    "PICATODO NARANJA - Precio: $2.40",
    "MAQUINA LIMPIA BROCHAS - Precio: $3.75",
    "ARDILLA ANTIESTRES - Precio: $0.95",
    "TORRE DE LUZ - Precio: $4.50",
    "AMBIENTADOR PARA AUTO - Precio: $0.75",
    "REPISA PLEGABLE - Precio: $1.95",
    "GANCHO MULTIUSO - Precio: $0.95",
    "SET DE CUCHILLOS - Precio: $7.50",
    "ALFOMBRAS UNO OCHENTA - Precio: $6.50",
    "ARBOL Y LUCES MULTICOLOR - Precio: $46.00",
    "ALFOMBRA REDONDA - Precio: $5.00",
    "SET DE CUCHARONES - Precio: $4.75",
    "MINI AIRE - Precio: $6.95",
    "ULTRA SONIC NEBULIZER - Precio: $8.75",
    "PROMO ALFOMBRA UNO OCHENTA - Precio: $5.00",
    "PROMO SETENTA Y CINCO TARJETAS - Precio: $1.00",
    "PROMO MAQUINA PARA MASCARILLAS - Precio: $14.50",
    "PROMO OCHO ESTRELLAS - Precio: $0.60",
    "PROMO VASOS PORTABLES - Precio: $1.05",
    "PROMO PLATERA LIMPIA OLLA Y ESCURRIDOR - Precio: $6.95",
    "PROMO LUCES MULTICOLOR DOS POR DOS - Precio: $4.95",
    "PROMO FOREVER Y CEPILLO - Precio: $8.00",
    "PROMO ALFOMBRA UNO OCHENTA - Precio: $5.00",
    "PROMO SETENTA Y CINCO TARJETAS - Precio: $1.00",
    "PROMO MAQUINA PARA MASCARILLAS - Precio: $14.50",
    "PROMO VASOS PORTABLES - Precio: $1.05",
    "PROMO LONCHERA CON PLASTILINAS - Precio: $3.85",
    "PROMO PLATERA LIMPIA OLLA Y ESCURRIDOR - Precio: $6.95",
    "PROMO LUCES MULTICOLOR DOS POR DOS - Precio: $4.95",
    "PROMO FOREVER Y CEPILLO - Precio: $8.00",
    "PROMO HAPPY NAPPER - Precio: $6.95",
    "PROMO TREINTA MASCARILLAS - Precio: $4.50",
    "PROMO PELOTA MAT Y BANDAS - Precio: $10.25",
    "PROMO WAFLERA SARTEN Y BATIDORA - Precio: $15.40",
    "PROMO MANTA Y ELEFANTE - Precio: $14.95",
    "PROMO ZAPATERA DOS CUERPOS - Precio: $12.50",
    "PROMO PULPO - Precio: $0.95",
    "PROMO LENTES DE CONTACTO - Precio: $5.30",
    "PROMO INFLADOR - Precio: $11.00",
    "PROMO MOLINO - Precio: $7.25",
    "PROMO CARPA TUNEL - Precio: $15.45",
    "PROMO LABIALES HUDA - Precio: $4.50",
    "PROMO ALFOMBRA VARIAS - Precio: $4.45",
    "PROMO CREPERA - Precio: $12.75",
    "PROMO MINI LAVADORA - Precio: $2.20",
    "PROMO ALCANCIA UNICORNIO - Precio: $4.75",
    "PROMO SECADOR MASCOTAS - Precio: $8.00",
    "PROMO BLUSA TERMICA - Precio: $2.20",
    "PROMO MASAJEADOR FACIAL - Precio: $4.90",
    "PROMO MASAJEADOR FACIAL - Precio: $4.95",
    "PROMO CEPILLO Y ONDULADOR - Precio: $9.75",
    "PROMO PORTA ROPA INTERIOR - Precio: $1.60",
    "PROMO PARRILLA - Precio: $8.75",
    "PROMO HAIRCHALK - Precio: $2.50",
    "PROMO BROCHAS MULTI COSMETIC - Precio: $6.50",
    "PROMO COMBO BLANQUEADOR - Precio: $6.65",
    "PROMO CEPILLO MULTIUSO - Precio: $11.40",
    "PROMO COMBO CELESTE - Precio: $4.25",
    "PROMO CINTILLO Y COLAGENOS - Precio: $3.35",
    "PROMO CORRECTOR DE ESPALDA - Precio: $2.20",
    "MASAJEADOR DHL - Precio: $9.50",
    "ASPIRADORA MANUAL - Precio: $5.30",
    "SPRAY ANTI RAYONES- Precio: $4.75",
    "RELOJ T QUINIENTOS - Precio: $14.95",
    "RELOJ HIWATCH - Precio: $16.00",
    "MESA PORTATIL CON VENTILADOR - Precio: $8.25 A PARTIR DE 3 UNIDADES $8.00 C/U",
    "NUEVO MASAJEADOR PARA AUTO - Precio: $12.00",
    "CAMARA DE BURBUJAS - Precio: $4.50",
    "SET RAYADOR - Precio: $4.95",
    "ROBOT BARREDOR - Precio: $12.00",
    "ASIENTO AZUL - Precio: $4.75",
    "PULPO ACUATICO- Precio: $6.25",
    "ALFOMBRAS DOS METROS - Precio: $18.00",
    "MANTA DOS METROS - Precio: $12.00",
    "VENTILADORES DE COLORES - Precio: $4.50",
    "COMBO CABALLERO - Precio: $11.25",
    "LAMPARITA REFLECTORA - Precio: $4.75",
    "COMBO CANGURO - Precio: $9.50",
    "ALCANCIA CAMION - Precio: $14.00",
    "JUEGO DE DADOS - Precio: $7.25",
    "MEDIANO INFLADOR DE LLANTAS - Precio: $3.95",
    "COMBO RELOJ PERFUME Y CINTURON - Precio: $8.50",
    "COLGADOR PLATEADO Y NEGRO - Precio: $9.25",
    "LAMPARA PARA UNAS - Precio: $4.95",
    "PORTA BRASIER - Precio: $1.75",
    "PARLANTE DE COLORES - Precio: $4.50",
    "PLASTILINA - Precio: $2.25",
    "RELOJ DE PARED - Precio: $4.50",
    "COMBO DE MAQUILLAJE - Precio: $6.75",
    "ALUMINIO ADHESIVO - Precio: $2.50",
    "SARTEN CUATRO EN UNO - Precio: $6.75",
    "MALETA MASCOTA - Precio: $15.50",
    "TRAPEADOR DE TELA - Precio: $2.85",
    "NUEVA PARRILLA - Precio: $9.50",
    "MESA CON RUEDAS - Precio: $13.50",
    "COMPRESOR - Precio: $8.00",
    "SPINNER POPI - Precio: $1.15",
    "ESFERAS NAVIDENAS - Precio: $8.80",
    "BALANZA DE CRISTAL - Precio: $6.75",
    "RELOJES CALVIN KLEIN - Precio: $4.90",
    "LUCES PARA ESPEJO - Precio: $4.25",
    "PLANCHA VAPOR - Precio: $8.50",
    "SET ROSA - Precio: $4.40",
    "COMBO DEPORTIVO - Precio: $11.00",
    "RELOJES COUPLE CORREA DE CUERO - Precio: $9.75",
    "RELOJES COUPLE CORREA METAL - Precio: $9.95",
    "COMBO FABIANA - Precio: $12.95",
    "ARBOL PINO - Precio: $45.00",
    "ARBOL Y ALFOMBRA PROMO - Precio: $45.00",
    "PROMO BLUE CINTILLO CREMA Y FOREVER - Precio: $3.45",
    "PROMO BLUE SEIS MASAJEADORES - Precio: $3.30",
    "PROMO BLUE ESENCIA PARA OJOS - Precio: $1.50",
    "PROMO BLUE LENTE DE CONTACTO - Precio: $5.75",
    "PROMO BLUE LUCES ESTRELLAS - Precio: $7.30",
    "PROMO BLUE TAPE FLEX - Precio: $0.65",
    "PROMO BLUE EXTRACTOR DE PUNTOS NEGROS - Precio: $3.80",
    "PROMO BLUE ALCANCIA - Precio: $4.25",
    "PROMO BLUE FOREVER Y EXTRACTOR - Precio: $5.25",
    "PROMO BLUE ONDU TRIPLE Y CEPILLO - Precio: $15.25",
    "PROMO BLUE DISPENSADOR DE AGUA - Precio: $2.50",
    "PROMO BLUE DOCE MASCARILLAS DORADAS - Precio: $6.50",
    "PROMO BLUE CEPILLO Y COMBO SKINCARE - Precio: $9.60",
    "PROMO BLUE MOLINO SPRAY TAPE - Precio: $9.15",
    "PROMO BLUE WAFLERA SARTEN Y BATIDORA - Precio: $15.65",
    "PROMO BLUE PLANCHA Y CEPILLO - Precio: $15.25",
    "PROMO BLUE SARTEN AGUJA Y WAFLERA - Precio: $10.60",
    "PROMO BLUE CINTILLO CREMA Y FOREVER - Precio: $3.45",
    "PROMO BLUE FILTROS DISPEN LIMPIA WAFLERA - Precio: $12.25",
    "PROMO BLUE CUCHARONES ALUMINIO TAPONES - Precio: $5.95",
    "PROMO BLUE ZOOVA - Precio: $5.45",
    "PROMO BLUE LUCES HADA - Precio: $4.50",
    "PROMO BLUE TECLADO - Precio: $3.50",
    "PROMO BLUE CARBON MASK - Precio: $1.50",
    "PROMO BLUE MASAJEADOR FACIAL - Precio: $4.00",
    "PROMO BLUE HUMIFICADOR FLORERO - Precio: $4.30",
    "PROMO BLUE ABRIGO - Precio: $4.50",
    "PROMO BLUE ALEJANDRA- Precio: $7.45",
    "TACHO Y TRAPEADOR - Precio: 9.75",
    "CARPA ROSADA - Precio: $16.00",
    "CAPTUS - Precio: $9.50",
    "ALCANCIA UNICORNIO - Precio: $4.95",
    "LUCES ARBOLES - Precio: $7.90",
    "LUCES CAMPANAS - Precio: $7.90",
    "LUCES OCHO METROS - Precio: $6.50",
    "ORGANIZADOR DE METAL  - Precio: $6.50",
    "FALDA DE ARBOL - Precio: $2.00",
    "TAPETE DE ENTRADA - Precio: $1.75",
    "DOS FORROS DE COJINES - Precio: $3.75",
    "AFEITADORA PARA HOMBRE - Precio: $5.95",
    "BEBEDERO MULTIUSO MASCOTAS - Precio: $6.50",
    "SET RAYADOR - Precio: $6.95",
    "ALCANCIA INFANTIL - Precio: $11.25",
    "PROMO BLUE ZAPATERA MULTI - Precio: $11.25",
    "PROMO BLUE COMBO NEON - Precio: $3.50",
    "PROMO BLUE MANTA BRILLANTE - Precio: $9.75",
    "PROMO BLUE MASAJEADOR DE AUTO - Precio: $11.25",
    "PROMO BLUE COMBO MADI - Precio: $10.95",
    "PROMO BLUE ARBOL LUCES Y FALDA - Precio: $44.00",
    "PROMO BLUE COMBO CAPTUS - Precio: $11.00",
    "PROMO BLUE GUANTES PARA MASCOTAS - Precio: $1.10",
    "PROMO BLUE WAFLERA - Precio: $8.95",
    "PROMO BLUE SEIS EXFO - Precio: $3.45",
    "PROMO BLUE COMBO NAVIDENO - Precio: $21.50",
    "PROMO BLUE COMBO TITANIUM - Precio: $10.95",
    "PROMO BLUE ORGANIZADOR CRISTAL - Precio: $7.95",
    "PROMO BLUE GDOS AUDIFONOS - Precio: $11.50",
    "PROMO BLUE HD AUDIFONOS - Precio: $9.75",
    "PROMO BLUE ARO ESFERA - Precio: $4.00",
    "PROMO BLUE FOCO PARLANTE - Precio: $9.95",
    "PROMO BLUE KIT EJERCITATE - Precio: $9.50",
    "PROMO BLUE MAQUINA PARA MASKS - Precio: $14.50",
    "PROMO GREEN OSO SET MUNECOS - Precio: $27.75",
    "PROMO GREEN ESCRITORIO CON RUEDAS - Precio: $19.95",
    "PROMO GREEN PASTILLERO - Precio: $3.40",
    "PROMO GREEN DIS GRANOS - Precio: $2.45",
    "PROMO GREEN HONGO - Precio: $2.75",
    "PROMO GREEN CORRECTOR PORSTURA - Precio: $1.95",
    "PROMO GREEN GAMERS AUDIFONOS - Precio: $9.05",
    "PROMO GREEN ALMOHADA - Precio: $3.25",
    "PROMO GREEN REDUCTOR MASAJEADOR - Precio: $10.50",
    "PROMO GREEN OSO REFLECTOR - Precio: $6.95",
    "PROMO GREEN CUERDA - Precio: $2.35",
    "PROMO GREEN HUEVERA FILTROS BATIDORA - Precio: $7.75",
    "PROMO GREEN RUEDA Y BANDAS - Precio: $4.75",
    "PROMO GREEN SARTEN WAFLERA AGUJA - Precio: $9.95",
    "PROMO GREEN ALUMINIO HORNILLA - Precio: $0.90",
    "PROMO GREEN DOS DIEZ ARBOL - Precio: $36.00",
    "PROMO GREEN RENO LARGO SET MUNECO - Precio: $19.95",
    "PROMO GREEN DOS CUARENTA ARBOL- Precio: $41.80",
    "PROMO GREEN UNO OCHENTA ARBOL - Precio: $26.50",
    "PROMO GREEN ZAPAETRA MULTI - Precio: $17.95",
    "PROMO GREEN MASAJEADOR FACIAL - Precio: $3.95",
    "PROMO GREEN ARBOL DOS DIEZ - Precio: $42.50",
    "HIELERA AZUL - Precio: $1.70",
    "RAYA AJO - Precio: $1.90 A PARTIR DE 3 UNIDADES $1.75",
    "CAR WASHER - Precio: $30.50",
    "DISPENSADOR DE ARROZ - Precio: $17.50",
    "ORG MAQUILLAJE GIRATORIO - Precio: $4.95",
    "VAPOR PLANCHA - Precio: $7.35",
    "MESA PARA COMER - Precio: $8.50",
    "FOCO CUATRO ALAS - Precio: $9.95",
    "MICRO PARA KIDS - Precio: $4.95",
    "CINTILLO Y COMBO BLANQUEADOR - Precio: $6.25",
    "MASCARILLA PUNTOS NEGROS - Precio: $1.65",
    "RELOJ PARA CABALLERO - Precio: $6.00",
    "REFRI PORTATIL - Precio: $22.75",
    "PROMO BLUE SET DE BROCHAS - Precio: $4.45",
    "PROMO BLUE JADE - Precio: $1.75",
    "PROMO BLUE ENTRAMIENTO PARA NINOS - Precio: $3.00",
    "PROMO BLUE REPELENTE - Precio: $0.60",
    "PROMO BLUE JUEGO SERUMS - Precio: $3.45",
    "PROMO BLUE HAPPY NAPPER - Precio: $6.95",
    "PROMO BLUE SESENTA COLLAGEN - Precio: $1.75",
    "PROMO BLUE SALTARIN - Precio: $1.95",
    "SET DE BANO NAVIDENO - Precio: $5.95 A PARTIR DE 3 UNIDADES 5.50 C/U",
    "SET DE BANO NAVIDENO - Precio: $5.95 A PARTIR DE 6 UNIDADES 4.95 C/U",
    "SET NAVIDENO - Precio: $5.95 A PARTIR DE 3 UNIDADES $5.50 C/U",
    "SET NAVIDENO - Precio: $5.95 A PARTIR DE 6 UNIDADES $4.95 C/U",
    "CAMINOS DE MESA - Precio: $4.00 A PARTIR DE 6 UNIDADES $3.20 C/U",
    "PROYECTOR DE LUCES NAVIDENA - Precio: $8.50",
    "ORGANIZADOR OCULTO - Precio: $11.25 A PARTIR DE 3 UNIDADES $11.00 C/U",
    "ORGANIZADOR ADHESIVO MULTIUSO - Precio: $8.75",
    "CORE SLIDE PEEL - Precio: $5.95",
    "FAJAS PARA DAMA - Precio: $2.75",
    "PROMO BLUE COMBO GABRIELA - Precio: $12.25",
    "PROMO BLUE TRIPLE - Precio: $8.95",
    "PROMO BLUE CUCHILLOS FILTROS - Precio: $7.50",
    "COMBO MARGARITA - Precio: $8.90",
    "CAJA DE MASCARILLAS - Precio: $1.95",
    "NUEVA FALDA DE ARBOL - Precio: $1.95",
    "FALDA DE ARBOL - Precio: $1.75",
    "PARAGUAS PARA AUTO - Precio: $6.50",
    "PROMO GREEN MUNECOS Y RODAPIE - Precio: $13.80",
    "PROMO GREEN ARBOL TRADICIONAL - Precio: $24.75",
    "PROMO GREEN UNO CINCUENTA ARBOL - Precio: $18.90",
    "PROMO GREEN FOLLAJE - Precio: $3.00 A PARTIR DE 6 UNIDADES $2.75 C/U",
    "PROMO GREEN CUATRO INDIVIDUALES PARA MESA - Precio: $4.25",
    "PROMO GREEN SEIS POP - Precio: $12.00",
    "PROMO GREEN CAMINO DE MESA - Precio: $3.75",
    "PROMO GREEN COBERTOR TRES PUESTOS - Precio: $7.95",
    "PROMO GREEN MICKEY POP - Precio: $2.35",
    "PROMO GREEN MAQUINA PARA HACER MASCARILLAS - Precio: $14.00",
    "PROMO GREEN ELEFANTE - Precio: $5.25",
    "PROMO GREEN MANTELES - Precio: $3.20",
    "ARBOL DE LUCES - Precio: $9.50",
    "PROMO BLUE COMBO PIES - Precio: $4.75",
    "PROMO BLUE TVBOX - Precio: $20.75",
    "PROMO BLUE PARRILLA - Precio: $8.50",
    "PROMO BLUE SALTARIN - Precio: $1.95",
    "PROMO BLUE MESA INFANTIL - Precio: $5.95",
    "PROMO BLUE PLANCHA VAPOR - Precio: $7.95",
    "PROMO BLUE CREPERA - Precio: $12.25",
    "PROMO BLUE NEON - Precio: $2.75",
    "PROMO BLUE SALTARIN - Precio: $1.95",
    "PROMO BLUE REPERO TRES CUERPOS - Precio: $18.75",
    "PROMO BLUE ZAPATERA - Precio: $5.80",
    "PROMO BLUE CEPILLO SECADOR - Precio: $5.95",
    "PROMO BLUE CASTILLO - Precio: $7.75",
    "PROMO BLUE CASTILLO Y NEON - Precio: $9.50",
    "PROMO BLUE SALTARIN - Precio: $1.95",
    "PROMO BLUE CREMA DEPILATORA - Precio: $1.90",
    "PROMO BLUE BATIDORA - Precio: $5.40",
    "PROMO BLUE ORGANIZADOR - Precio: $12.00",
    "PROMO BLUE REPISA OCULTA - Precio: $8.80",
    "PROMO BLUE FOCO PARLANTE - Precio: $3.40",
    "PROMO BLUE NOVA Y CEPILLO - Precio: $9.50",
    "PROMO BLUE COMBO ARO - Precio: $11.95",
    "PROMO BLUE SOMBRA PRO - Precio: $8.90",
    "PROMO BLUE DOS MUNECOS NAVIDENOS - Precio: $13.30",
    "PROMO BLUE M DOS MUNECOS - Precio: $14.50",
    "PROMO BLUE TRES MUNECOS NAVIDENOS - Precio: $27.75",
    "PROMO BLUE BATIDORA - Precio: $5.40",
    "PROMO GREEN MICKEY  - Precio: $15.75",
    "PROMO GREEN IMPRESORA - Precio: $12.50 A PARTIR DE 6 UNIDADES $12.25 C/U",
    "PROMO GREEN DOS M ALFOMBRA - Precio: $18.50",
    "PROMO GREEN PLATERA DOS POZOS - Precio: $25.95",
    "PROMO GREEN ARBOL UN METRO - Precio: $8.75",
    "PROMO GREEN PLATERA COLORES - Precio: $11.75",
    "PROMO GREEN DOS P DEDADELES - Precio: $0.75",
    "PROMO GREEN PLATEADOS MUNECOS - Precio: $19.50",
    "PROMO GREEN UNO OCHENTA ARBOL - Precio: $26.50",
    "PROMO GREEN SET RENO MUNECOS - Precio: $23.85",
    "PROMO GREEN DOS MUNECOS - Precio: $12.10",
    "PRO ABR CEPILLO Y FOREVER - Precio: $7.75",
    "PRO ABR ROPERO TRES CUERPO - Precio: $18.75",
    "PRO ABR SET BLANQUEADOR - Precio: $2.80",
    "PRO ABR FOCO Y TIKTOK - Precio: $6.75",
    "PRO ABR SALIDA DE BANO - Precio: $5.50",
    "PRO ABR COLAGENOS Y CINTILLO - Precio: $3.45",
    "PRO ABR COBO DE MAQUILLAJE - Precio: $6.95",
    "PRO ABR SET DE MAQUILLAJE - Precio: $7.55",
    "PRO ABR COMBO LOVE - Precio: $11.95",
    "PRO ABR MICKEY Y MINI - Precio: $16.00",
    "PRO ABR POP NAVIDENO - Precio: $2.75",
    "PRO ABR ARO DE LUZ - Precio: $7.65",
    "PRO ABR LUCES ESTRELLAS - Precio: $6.50",
    "PRO ABR ORGA OCULTO - Precio: $7.45",
    "PRO ABR HAPPY NAPPER - Precio: $6.75",
    "PRO ABR MASAJEADOR FACIAL - Precio: $3.80",
    "PRO ABR PASTILLERO - Precio: $3.40 A PARTIR DE 3 UNIDADES $3.25 C/U",
    "PRO ABR WAFLERA - Precio: $8.60",
    "PRO ABR SEIS EXFO- Precio: $3.45",
    "PRO ABR PORTA MASCARILLA - Precio: $0.75",
    "PRO ABR LUCES DE ARBOL - Precio: $9.50",
    "PRO ABR TRES MUNECOS - Precio: $27.75",
    "PRO ABR PLATEADOS MUNECOS - Precio: $29.75",
    "PRO ABR DORADOS MUNECOS - Precio: $29.75",
    "PRO ABR ORGANIZADOR CRISTAL - Precio: $7.50",
    "PRO ABR FOLLAJE - Precio: $2.75",
    "PRO ABR TENAZA Y CEPILLO - Precio: $14.75",
    "PRO ABR COMBO SPA - Precio: $3.90",
    "PRO ABR LENTE DE CONTACTO - Precio: $5.50",
    "PRO ABR DIS PASTA - Precio: $4.25",
    "PRO ABR COBO TITANIUM - Precio: $10.75",
    "PRO ABR FOCO TRES ALAS - Precio: $3.25",
    "PRO ABR FUNDA DE GANCHOS - Precio: $0.45",
    "PRO ABR ARBOL - Precio: $42.50",
    "PRO ABR SEIS POPS - Precio: $11.50",
    "PRO ABR CEPILLO Y SONAR - Precio: $15.50",
    "PRO ABR COMBO DESAYUNO - Precio: $9.75",
    "PRO ABR KIT EJERCITATE - Precio: $8.95",
    "PRO ABR COLGADOR Y ZAPATERA - Precio: $16.30",
    "PRO ABR COMBO WAFLERA Y BATIDORA - Precio: $14.45",
    "PRO ABR RODAPIE - Precio: $1.50 A PARTIR DE 12 UNIDADES $1.30 C/U",
    "PRO ABR EXTRACTOR DE PUNTOS NEGROS - Precio: $3.75",
    "PRO ABR MAQUINA PARA CALLOS - Precio: $2.25",
    "PRO ABR NOVA Y SONAR - Precio: $12.50",
    "PRO ABR ARBOL DOS CUARENTA - Precio: $41.80",
    "PRO ABR ARBOL DOS CON DIEZ - Precio: $36.00",
    "PRO ABR ARBOL UNO OCHENTA - Precio: $24.75",
    "PRO ABR ARBOL UNO CINCUENTA - Precio: $18.90",
    "PRO ABR FORRO DE SILLA NAV - Precio: $2.25",
    "PRO ABR F SILLA NAV - Precio: $2.75",
    "PRO ABR LUCES SOLARES - Precio: $5.50",
    "PRO ABR SET BABY - Precio: $2.95",
    "PRO ABR TRES CAJAS NAVIDENAS - Precio: $24.95",
    "PRO ABR POP CROSSBODY - Precio: $7.00",
    "PRO ABR POP MONEDERO - Precio: $1.95",
    "PRO ABR LUCES AMARILLAS - Precio: $7.90",
    "PRO ABR LUCES DIEZ FOCOS OCHO M - Precio: $8.50",
    "PRO ABR LUCES MULTICOLOR - Precio: $7.90",
    "PRO ABR ALFOMBRA - Precio: $16.95",
    "PRO ABR ARBOL CON NIEVE - Precio: $20.75",
    "PRO ABR OSO REFLECTOR - Precio: $6.95",
    "PRO ABR CANASTA REFRI - Precio: $0.75",
    "PRO ABR PULIDOR - Precio: $2.10",
    "PRO ABR SEIS ESTRELLAS - Precio: $2.75",
    "PRO ABR LUCES DIEZ FOCOS TRES M - Precio: $3.95",
    "PRO ABR BATIDORA - Precio: $5.45",
    "PRO ABR LUZ TIKTOK - Precio: $6.25",
    "PRO ABR COMBO PLATERA ACEITERO - Precio: $6.75",
    "PRO ABR CHOCO HUEVERA - Precio: $10.90",
    "PRO ABR MOLINO ACEITERO - Precio: $9.05",
    "PRO ABR TENAZA TRIPLE - Precio: $8.75",
    "PRO ABR GUANTES LIMPIA OLLA - Precio: $3.25",
    "PRO ABR RENO TRES MUNECOS - Precio: $19.95",
    "PRO ABR LUZ HADA - Precio: $0.25",
    "PRO ABR VELA - Precio: $3.25",
    "PRO ABR LUZ LED MANGUERA - Precio: $6.75",
    "PRO ABR URINARIO - Precio: $2.95",
    "PRO ABR OR DE PLASTICO - Precio: $4.65",
    "PRO ABR DIS MEDIANO - Precio: $2.45",
    "PRO ABR CARPA CIRCO - Precio: $7.75",
    "PRO ABR COMPRESOR MEDIANO - Precio: $3.70",
    "PRO ABR MANTELES - Precio: $3.20",
    "PRO ABR SART ELECTRICO - Precio: $10.50",
    "PRO ABR BROWNIES - Precio: $10.95",
    "PRO ABR ROPERO DOS CUERPOS - Precio: $11.95",
    "PRO ABR PESTANAS Y DELINEADOR - Precio: $1.75",
    "PRO ABR PLATERA DE COLORES - Precio: $11.45",
    "PRO ABR DISPENSADOR DE BOTELLA - Precio: $1.50",
    "PRO ABR MASAJEADOR REDUCTOR - Precio: $9.75",
    "PRO ABR ABRIGO - Precio: $4.50",
    "PRO ABR ESFERAS - Precio: $8.00",
    "PRO ABR PROTECTOR DE BRA - Precio: $0.95",
    "PRO ABR MAGIC PAD - Precio: $3.25",
    "PRO ABR PARLANTE CILINDRICO - Precio: $3.95",
    "PRO ABR LENTE SIN LIQUIDO - Precio: $3.25 A PARTIR DE 6 UNIDADES $3.00 C/U",
    "PRO ABR CERCA DE HOJAS - Precio: $8.75",
    "PRO ABR CEPILLO MULTI - Precio: $10.95",
    "PRO ABR - Precio: $11.95",
    "PRO ABR RODAPIE PROMO CON MUNECO - Precio: $1.00",
    "FOCO LED PARLANTE - Precio: $10.25",
    "TRES HUEVITOS - Precio: $1.00",
    "DINOSAURIOS - Precio: $1.60",
    "COMBO SPORT - Precio: $7.55",
    "NUEVO COMBO CABALLERO - Precio: $11.00",
    "COMBO E FAVORITO - Precio: $9.75",
    "NUEVO SPLASH Y CREMA - Precio: $3.85",
    "COLGADOR CON GANCHOS - Precio: $8.95",
    "COBIJA DOS M - Precio: $10.50",
    "TIKTOK LED CON BLUETOOH - Precio: $6.50",
    "COMBO E FAVORITO - Precio: $9.75",
    "PICATODO DE METAL - Precio: $9.50",
    "VOICE TOY - Precio: $6.50",
    "AUDIFONO GATITO - Precio: $5.50 A PARTIR DE 3 UNIDADES $5.00",
    "PET ZONE - Precio: $3.95",
    "MOLINO DE GRANOS - Precio: $6.75",
    "DIEZ PASTILLAS PARA BANO - Precio: $0.95",
    "PRO ABR SET EVERYWERE- Precio: $9.25",
    "PRO ABR SET PALETA VERTE - Precio: $12.50",
    "PRO ABR COMBO GUANTES FLEX TAPE - Precio: $2.75",
    "PRO ABR SET ROSTRO LIMPIO - Precio: $5.60",
    "PRO ABR SET CUTIS JOVEN - Precio: $5.75",
    "PRO ABR P UN POZO - Precio: $21.00 A PARTIR DE 3 UNIDADES $20.50",
    "PRO ABR MESA - Precio: $7.95",
    "PRO ABR FAJA DE HOMBRE - Precio: $3.50",
    "PRO ABR PORTA LAPTOP - Precio: $10.50",
    "PRO ABR SET DEPORTIVO - Precio: $9.25",
    "PRO ABR COMBO TRATAMIENTO BLANQUEADOR - Precio: $4.75",
    "PRO ABR REFRI - Precio: $21.95",
    "PRO ABR HUMIFICADOR COCO - Precio: $4.25",
    "PRO ABR SET DEPILATE - Precio: $9.80",
    "PRO ABR OR TRES PISOS - Precio: $13.50",
    "PRO ABR OR SMALL CRISTAL - Precio: $4.25",
    "PRO ABR FUNDA DE CUATRO COLGADORES - Precio: $0.75",
    "PRO ABR CAJAS DE REGALO - Precio: $22.50",
    "PRO ABR PICATODO METALICO - Precio: $8.50",
    "PRO ABR ARBOL DE LUZ - Precio: $8.95",
    "PRO ABR HEADPHONES DE COLORES - Precio: $4.25",
    "PRO ABR BICI ELECTRICA - Precio: $90.00",
    "PRO ABR TAZA LEGO - Precio: $3.75",
    "PRO ABR SET BABY - Precio: $3.75",
    "PRO ABR DUENDES - Precio: $3.95",
    "PRO ABR CANGUILERA - Precio: $9.75",
    "PRO ABR SEIS TOALLAS DE COCINA - Precio: $2.65",
    "PRO ABR KIT EJERCICIO - Precio: $8.25",
    "PRO ABR LUCES METALICAS TRES M - Precio: $1.95",
    "PRO ABR LUZ HADA - Precio: $1.50",
    "PRO ABR MESA LAPTOP - Precio: $5.50",
    "OCHO PULGADAS ARO - Precio: $4.75",
    "SET PINK - Precio: $5.95",
    "PLANCHA ELECTRICA - Precio: $7.95",
    "GEL ANTIACNE - Precio: $1.95",
    "COLCHONETA INFLABLE - Precio: $16.50",
    "GEL ANTIACNE - Precio: $14.95",
    "ORGANIZADOR MEDIANO - Precio: $3.50",
    "TRES PORTA ARMADORES - Precio: $1.00",
    "PRO ABR POPI ANTIFAZ - Precio: $2.75",
    "PRO ABR NEW POPPI - Precio: $2.50",
    "PRO ABR TREE MULTICOLOR - Precio: $5.85",
    "PRO ABR TRES M CERCA HOJAS- Precio: $9.75",
    "PRO ABR COMBO ARBOL DORADO DOS DIEZ - Precio: $51.25",
    "PRO ABR ADORNO NAVIDENO - Precio: $0.80",
    "PRO ABR DOS MUNECOS - Precio: $13.25",
    "PRO ABR ADORNO LENTEJUELAS - Precio: $1.10",
    "PRO ABR JUEGO POP IT - Precio: $7.50",
    "PRO ABRSOLO ARBOL DORADO - Precio: $40.00",
    "PRO ABR COBIJA Y ELEFANTE - Precio: $11.95",
    "PRO ABR ALFOMBRA DOS M - Precio: $1.50",
    "PRO ABR TRES CUERPOS - Precio: $18.75",
    "PRO ABR DOS CUERPOS - Precio: $12.95",
    "PRO ABR PELOTA Y BANDAS - Precio: $5.50",
    "PRO ABR CARPA Y PAD - Precio: $10.75",
    "PRO ABR BOWL - Precio: $0.95",
    "PRO ABR ADORNOS VEINTIUN CEN - Precio: $0.85",
    "PRO ABR LORO - Precio: $9.00",
    "PRO ABR GUIRNALDAS - Precio: $2.35",
    "PRO ABR MASCARAS - Precio: $4.50",
    "PRO ABR MUNECOS NAVI TRIO - Precio: $16.00",
    "PRO ABR INDIVIDUAL MUNECO - Precio: $8.00",
    "PRO ABR ARBOL CON LUCES INCORPORADAS - Precio: $35.00",
    "PRO ABR NEW MONEDERO - Precio: $2.25",
    "PRO ABR CARTUCHERA POP IT - Precio: $3.75",
    "PRO ABR CAJA CON HERRA - Precio: $3.50",
    " MINIUMS DISPENSADOR - Precio: $4.75",
    "CORTINA LUCES AMARILLAS - Precio: $9.00",
    " COMBO MIFUDUO - Precio: $5.75",
    " JENGA GAME - Precio: $7.00",
    "REPISA BLANCA DOS COMPAR - Precio: $5.95",
    "BEBEDERO - Precio: $5.50",
    "COMEDERO - Precio: $5.50",
    "CIEN FUNDAS - Precio: $1.50",
    "ENCHUFE ADAPTADOR - Precio: $0.95",
    "MINI ENCHUFE CON WIFI - Precio: $5.50",
    "CAMARA HD - Precio: $22.95",
    "PRO ABR RENO LUZ INCORPORADA - Precio: $13.50",
    "D ABR CAPTUS BAILARÍN - Precio: $10.00",
    "D ABR ADORNITOS NAVI - Precio: 0.95",
    "D ABR SET CUATRO PIEZAS - Precio: $1.75",
    "D ABR SARTÉN ELÉCTRICA - Precio: $5.60",
    "D ABR LÁMPARA REFLECTORA - Precio: $4.10",
    "D ABR CORTINA HADA - Precio: $4.45",
    "D ABR COMBO CELESTE - Precio: $2.25",
    "BASE CUATRO RUEDAS - Precio: $9.95",
    "D ABR DISPEN DE AGUA - Precio: $2.50",
    "D ABR DOCENA DE RODAPIE - Precio: $15.00",
    "D ABR PLANCHA SONAR - Precio: $8.65",
    "D ABR MASCARILLA DE HUEVO - Precio: $1.80",
    "D ABR JABON FACIAL - Precio: $1.95",
    "D ABR FUNDAS DESINFECTANTES - Precio: $1.95",
    "D ABR SALTARIN - Precio: $2.25",
    "D ABR COMBO FOREVER - Precio: $3.75",
    "D ABR ZAPATERA - Precio: $5.75",
    "D ABR CHOCOLATERA - Precio: $7.95",
    "D ABR LIGAS D RESISTENCIA - Precio: $3.10",
    "D ABR PORTA ROPA IN - Precio: $1.60",
    "D ABR PLATERA DOS POZOS - Precio: $26.50",
    "CINCO CREMAS - Precio: $1.95",
    "BATIDORA CON RECIPIENTE - Precio: $16.00",
    "MASCARILLA PARA PIES - Precio: $1.25",
    "COMBO FOSSIL - Precio: $11.50",
    "JUEGO LEGOS POP IT - Precio: $4.25",
    "PRODUCTO PARA FRUTAS - Precio: $1.75",
    "LIMPIADOR FACIAL - Precio: $2.95",
    "EXTENSION DE ENCHUFES - Precio: $2.95",
    "EXTENSION DE ENCHUFES - Precio: $4.75",
    "DOS ESTRELLAS DE ADORNO - Precio: $0.85",
    "MAYA PARA DECORAR ÁRBOL - Precio: $3.75",
    "P ABR COMBO LIMPIEZA - Precio: $2.65",
    "P ABR COMBO CUCHARONES - Precio: $6.95",
    "P ABR COMBO C - Precio: $7.25",
    "P ABR COMBO C - Precio: $1.80",
    "P ABR COMBO H - Precio: $4.60",
    "P ABR COMBO G - Precio: $3.00",
    "P ABR COMBO J - Precio: $11.50",
    "P ABR SET E - Precio: $9.75",
    "P ABR CORONA PARA PUERTA - Precio: $5.75",
    "P ABR COMBO K - Precio: $7.95",
    "P ABR TAPETE PARA ENTRADA - Precio: $2.05",
    "P ABR COMBO SMILE - Precio: $6.75",


];